### ISSUE TITLE
Crash on 1.19.2

### ISSUE THREAD

**Issue by andreasdc** [xCollateral/VulkanMod#131]
When you join the server and connection is cancelled, you get crashed.
A fatal error has been detected by the Java Runtime Environment:
EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff9b0f2c42a, pid=9536, tid=13384
JRE version: Java(TM) SE Runtime Environment (18.0.1.1+2) (build 18.0.1.1+2-6)
Java VM: Java HotSpot(TM) 64-Bit Server VM (18.0.1.1+2-6, mixed mode, sharing, tiered, compressed class ptrs, z gc, windows-amd64)
Problematic frame:
C 0x00007ff9b0f2c42a
No core dump will be written. Minidumps are not enabled by default on client versions of Windows

**Comment by mmmmmmmmmmmmmmmmaly** [comment]
same
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'VulkanMod' (vulkanmod) 0.1.8 with any version that is compatible with:
		 - minecraft 1.19.2
Unmet dependency listing:
	 - Mod 'VulkanMod' (vulkanmod) 0.1.8 requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by mmmmmmmmmmmmmmmmaly** [comment]
fix
https://www.curseforge.com/minecraft/mc-mods/vulkanmod

**Comment by UltraBlackLinux** [comment]
It's not fixed yet. It wants 1.18 or 1.19, but a wildcard is missing so it only supports the major versions

**Comment by xCollateral** [comment]
Is this happening on new version?

**Comment by soshimee** [comment]
I have the same issue.
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff89d90e0a7, pid=5776, tid=3000
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.2+8 (17.0.2+8) (build 17.0.2+8)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (17.0.2+8, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# 
C  0x00007ff89d90e0a7
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\user\AppData\Roaming\PrismLauncher\instances\Quilt 1.19.3\.minecraft\hs_err_pid5776.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```
Reproduced with 1.19.3 no other mods.
Also that incompatible mod set thing is not the same issue.

**Comment by joncooke** [comment]
@xCollateral As previous commenter noted, ignore the incompatible mod set part, that diverted the whole bug report.

Can confirm on 1.19.2 the original EXCEPTION_ACCESS_VIOLATION problem is seen.

Running Windows 11 and have tried with updated Vulkan drivers (as of the date of writing this comment) and with different versions of Java (in case that made a difference) but see the same exception every time.

Am happy to provide whatever further information is required, or to try things to resolve if that would help.

**Comment by xCollateral** [comment]
Is this still happening on latest version?

**Comment by oxzin** [comment]
I also have the same problem whenever i press the tab key
