### ISSUE TITLE
Can`t be working at Minecraft 1.19.x

### ISSUE THREAD

**Issue by AkarinLiu** [xCollateral/VulkanMod#146]
## Screenshot
![image](https://user-images.githubusercontent.com/58081491/204494047-89b7972b-4115-4760-a6dd-cef42a8208ae.png)

## Log File
[17:38:59] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.10
[17:38:59] [ForkJoinPool-1-worker-2/WARN]: Mod com_github_wearblackallday_javautils uses the version bd58640372 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'bd58640372'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[17:39:00] [main/WARN]: Mod resolution failed
[17:39:00] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED vulkanmod 0.1.8 {depends minecraft @ [1.18.x]}, ROOT_FORCELOAD_SINGLE vulkanmod 0.1.8]
[17:39:00] [main/INFO]: Reason: [HARD_DEP vulkanmod 0.1.8 {depends minecraft @ [1.18.x]}]
[17:39:00] [main/INFO]: Fix: add [], remove [], replace [[vulkanmod 0.1.8] -> add:vulkanmod 1 ([(-��,��)])]
[17:39:01] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'VulkanMod' (vulkanmod) 0.1.8 with any version that is compatible with:
		 - minecraft 1.19.2
Unmet dependency listing:
	 - Mod 'VulkanMod' (vulkanmod) 0.1.8 requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?]

**Comment by xCollateral** [comment]
You downloaded wrong version, try using version for 1.19.x
