### ISSUE TITLE
Crashing at high render distances

### ISSUE THREAD

**Issue by TheBeautyLlama** [xCollateral/VulkanMod#153]
```
[18:08:25] [Server thread/INFO]: SausageKiller218 joined the game
[18:08:26] [Render thread/INFO]: Loaded 0 advancements
[18:08:50] [Server thread/INFO]: Saving and pausing game...
[18:08:50] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[18:08:50] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[18:08:50] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[18:09:07] [Worker-Main-18/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-18/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-18/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-18/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-18/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-19/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-19/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-19/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-19/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-19/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-19/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-19/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-19/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:07] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-19/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-19/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-30/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-30/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-30/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-30/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-30/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-30/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-30/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-30/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-30/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-30/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-30/WARN]: Clearing BufferBuilder with unused batches
[18:09:08] [Worker-Main-30/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-30/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-30/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-30/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-30/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-19/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-19/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-19/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-20/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-20/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-20/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-20/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-20/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-20/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-20/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-18/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-18/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-18/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-18/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-18/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-18/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-18/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-18/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-24/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-24/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-24/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-24/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-24/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-24/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-24/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-24/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-24/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-24/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-24/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-31/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
[18:09:09] [Worker-Main-17/WARN]: Clearing BufferBuilder with unused batches
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2022-12-13 18:09:09
Description: Rendering chunk

java.lang.RuntimeException: Failed to create buffer:-2
	at net.vulkanmod.vulkan.memory.MemoryManager.createBuffer(MemoryManager.java:75)
	at net.vulkanmod.vulkan.memory.MemoryManager.createBuffer(MemoryManager.java:109)
	at net.vulkanmod.vulkan.memory.MemoryTypes$DeviceLocalMemory.createBuffer(MemoryTypes.java:60)
	at net.vulkanmod.vulkan.memory.Buffer.createBuffer(Buffer.java:26)
	at net.vulkanmod.vulkan.memory.VertexBuffer.createVertexBuffer(VertexBuffer.java:23)
	at net.vulkanmod.vulkan.memory.VertexBuffer.<init>(VertexBuffer.java:17)
	at net.vulkanmod.render.VBO.configureVertexFormat(VBO.java:54)
	at net.vulkanmod.render.VBO.upload_(VBO.java:42)
	at net.minecraft.class_291.method_1352(class_291.java:552)
	at net.vulkanmod.render.chunk.TaskDispatcher.doUploadChunkLayer(TaskDispatcher.java:190)
	at net.vulkanmod.render.chunk.TaskDispatcher.lambda$scheduleUploadChunkLayer$6(TaskDispatcher.java:183)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1810)
	at net.vulkanmod.render.chunk.TaskDispatcher.uploadAllPendingUploads(TaskDispatcher.java:173)
	at net.vulkanmod.render.chunk.WorldRenderer.compileChunks(WorldRenderer.java:394)
	at net.minecraft.class_761.method_3269(class_761.java:3512)
	at net.minecraft.class_761.method_22710(class_761.java:1243)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.vulkanmod.vulkan.memory.MemoryManager.createBuffer(MemoryManager.java:75)
	at net.vulkanmod.vulkan.memory.MemoryManager.createBuffer(MemoryManager.java:109)
	at net.vulkanmod.vulkan.memory.MemoryTypes$DeviceLocalMemory.createBuffer(MemoryTypes.java:60)
	at net.vulkanmod.vulkan.memory.Buffer.createBuffer(Buffer.java:26)
	at net.vulkanmod.vulkan.memory.VertexBuffer.createVertexBuffer(VertexBuffer.java:23)
	at net.vulkanmod.vulkan.memory.VertexBuffer.<init>(VertexBuffer.java:17)
	at net.vulkanmod.render.VBO.configureVertexFormat(VBO.java:54)
	at net.vulkanmod.render.VBO.upload_(VBO.java:42)
	at net.minecraft.class_291.method_1352(class_291.java:552)
	at net.vulkanmod.render.chunk.TaskDispatcher.doUploadChunkLayer(TaskDispatcher.java:190)
	at net.vulkanmod.render.chunk.TaskDispatcher.lambda$scheduleUploadChunkLayer$6(TaskDispatcher.java:183)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1810)
	at net.vulkanmod.render.chunk.TaskDispatcher.uploadAllPendingUploads(TaskDispatcher.java:173)
	at net.vulkanmod.render.chunk.WorldRenderer.compileChunks(WorldRenderer.java:394)
	at net.minecraft.class_761.method_3269(class_761.java:3512)
	at net.minecraft.class_761.method_22710(class_761.java:1243)

-- Affected level --
Details:
	All players: 1 total; [class_746['SausageKiller218'/44, l='ClientLevel', x=460.50, y=189.03, z=1112.53]]
	Chunk stats: 5041, 3653
	Level dimension: minecraft:overworld
	Level spawn location: World: (-34,63,528), Section: (at 14,15,0 in -3,3,33; chunk contains blocks -48,-64,528 to -33,319,543), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,-64,512 to -1,319,1023)
	Level time: 12713 game time, 12713 day time
	Server brand: quilt
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_43589(class_310.java:856)
	at net.minecraft.class_310.method_1514(class_310.java:757)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.5, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1948254208 bytes (1858 MiB) / 6442450944 bytes (6144 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 6800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 68 Stepping 1
	Microarchitecture: Zen 3
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x1681
	Graphics card #0 versionInfo: DriverVersion=31.0.12029.10015
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 6.40
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 6.40
	Memory slot #1 type: Unknown
	Memory slot #2 capacity (MB): 4096.00
	Memory slot #2 clockSpeed (GHz): 6.40
	Memory slot #2 type: Unknown
	Memory slot #3 capacity (MB): 4096.00
	Memory slot #3 clockSpeed (GHz): 6.40
	Memory slot #3 type: Unknown
	Virtual memory max (MB): 19652.95
	Virtual memory used (MB): 18511.73
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 599.80
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms6144m -Xmx6144m
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: 1386x1481
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'quilt'; Server brand changed to 'quilt'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: AMD Ryzen 7 6800H with Radeon Graphics 
	Server Running: true
	Player Count: 1 / 8; [class_3222['SausageKiller218'/44, l='ServerLevel[New World]', x=460.50, y=189.03, z=1112.53]]
	Data Packs: vanilla
	World Generation: Stable

```

**Comment by xCollateral** [comment]
It seems there's not enough vram, try allocating less memory to jvm.
