### ISSUE TITLE
java.lang.RuntimeException: Device does not support dynamic rendering feature.

### ISSUE THREAD

**Issue by wb1016** [xCollateral/VulkanMod#243]
log file: https://paste.ee/p/bV4JD
```---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2023-05-23 19:51:45
Description: Initializing game

java.lang.RuntimeException: Device does not support dynamic rendering feature.
	at net.vulkanmod.vulkan.Vulkan.createLogicalDevice(Vulkan.java:404)
	at net.vulkanmod.vulkan.Vulkan.initVulkan(Vulkan.java:144)
	at net.vulkanmod.vulkan.VRenderSystem.initRenderer(VRenderSystem.java:59)
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:1504)
	at net.minecraft.class_310.<init>(class_310.java:517)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```
crash on startup.
hardware specs: Ryzen 5900HX with Radeon graphics
JVM: Sapmachine 20.1
arguments: `-XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:-UseParallelGC -XX:-UseG1GC -XX:+UseZGC`

**Comment by wb1016** [comment]
haha my bad
