### ISSUE TITLE
crash on startup with amd graphics

### ISSUE THREAD

**Issue by ghost** [xCollateral/VulkanMod#249]
In the log file:
[Render thread/ERROR]: 
Device 0: AMD Radeon(TM) Graphics
Unsupported extensions: [VK_KHR_dynamic_rendering]
Swapchain supported: true

driver version: 30.0.13014.4003
vulkan instance version: 1.2.176

**Comment by Palibrix** [comment]
Same think with Vega 7 and Ryzen 5 5500u even without other mods
java.lang.RuntimeException: Failed to find a suitable GPU
	at net.vulkanmod.vulkan.Vulkan.pickPhysicalDevice(Vulkan.java:354)
	at net.vulkanmod.vulkan.Vulkan.initVulkan(Vulkan.java:144)
	at net.vulkanmod.vulkan.VRenderSystem.initRenderer(VRenderSystem.java:59)
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:1504)
	at net.minecraft.class_310.<init>(class_310.java:517)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	
	Device 0: AMD Radeon(TM) Graphics
Unsupported extensions: [VK_KHR_dynamic_rendering]
Swapchain supported: true

**Comment by thr3343** [comment]
As xCollateral mentioned in some other issues, try updating the iGPU drivers if possible as Dynamic Rendering needs a relatively recent later 2022 and/or early 2023 driver to support iirc. 

That big problem/issue rn, is that some intel iGPUs seem to have been dropped from support from September 2022, and therefore were never updated to receive full Dynamic Rendering support, which is what is causing part of the problem afaik.

Thankfully, it is definately possible to remove Dynamic Rendering with no FPS drawbacks at all afaik, but it needs some questionable/semi-invasive refactoring that may cause issues/bugs with the mod longer term, so it may but be the best idea afaik.

**Comment by xCollateral** [comment]
It should be fixed.
