### ISSUE TITLE
[BUG] Crash after tab-out

### ISSUE THREAD

**Issue by snailcreature** [xCollateral/VulkanMod#256]
Game crashes with black screen after tabbing out of Minecraft and attempting to reopen it. The below crash readout from the latest log. 

```bash
java.lang.RuntimeException: Failed to present swap chain image
	at net.vulkanmod.vulkan.Drawer.drawFrame(Drawer.java:418) ~[VulkanMod_1.20.1-0.3.2.jar:?]
	at net.vulkanmod.vulkan.Drawer.submitDraw(Drawer.java:147) ~[VulkanMod_1.20.1-0.3.2.jar:?]
	at net.minecraft.class_310.handler$boe000$vulkanmod$submitRender(class_310.java:15552) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1241) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[fabric-loader-0.14.21-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
[00:27:46] [Render thread/ERROR]: Unhandled game exception
java.lang.NullPointerException: Cannot invoke "net.vulkanmod.vulkan.Framebuffer.scissor(org.lwjgl.system.MemoryStack)" because "net.vulkanmod.vulkan.Drawer.getInstance().boundFramebuffer" is null
	at net.vulkanmod.vulkan.Drawer.resetScissor(Drawer.java:671) ~[VulkanMod_1.20.1-0.3.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.disableScissor(RenderSystem.java:2126) ~[client-intermediary.jar:?]
	at fudge.notenoughcrashes.utils.GlUtil.resetState(GlUtil.java:27) ~[notenoughcrashes-4.4.4+1.20.1-fabric.jar:?]
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.resetStates(InGameCatcher.java:41) ~[notenoughcrashes-4.4.4+1.20.1-fabric.jar:?]
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:32) ~[notenoughcrashes-4.4.4+1.20.1-fabric.jar:?]
	at net.minecraft.class_310.modify$bgh000$notenoughcrashes$atTheEndOfSecondCatchBeforePrintingCrashReport(class_310.java:14074) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:829) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[fabric-loader-0.14.21-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
```

[View full latest.log](https://github.com/xCollateral/VulkanMod/files/11827057/latest.log).

[View full modlist](https://legacy.curseforge.com/minecraft/modpacks/client-for-beginners) (Version 1.0.1). Additional mods: Vulkan Renderer. Resource Packs: 
![image](https://github.com/xCollateral/VulkanMod/assets/26686171/92b5cc01-baa1-47c5-9bef-21717466c1c2)

System: Windows 11, [NUC8i7HVK](https://www.intel.co.uk/content/www/uk/en/products/sku/126143/intel-nuc-kit-nuc8i7hvk/specifications.html) machine, 16GB RAM

**Comment by xCollateral** [comment]
This should be fixed.
