### ISSUE TITLE
Crash on launch on macOS using PolyMC

### ISSUE THREAD

**Issue by douira** [xCollateral/VulkanMod#26]
I followed the posted instructions on installing for macOS (Monterey). It crashes with the following error on launch:

```
[00:44:29] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.7
[00:44:29] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[00:44:29] [main/INFO]: Loading 24 mods:
	- fabricloader 0.14.7
	- java 17
	- minecraft 1.18.2
	- org_joml_joml 1.10.4 via vulkanmod
	- org_lwjgl_lwjgl 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-glfw 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-glfw_natives-linux 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-glfw_natives-windows 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-openal 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-openal_natives-linux 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-openal_natives-windows 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-shaderc 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-shaderc_natives-linux 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-shaderc_natives-windows 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-stb 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-stb_natives-linux 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-stb_natives-windows 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-vma 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-vma_natives-linux 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-vma_natives-windows 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl-vulkan 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl_natives-linux 3.3.1 via vulkanmod
	- org_lwjgl_lwjgl_natives-windows 3.3.1 via vulkanmod
	- vulkanmod 0.1.4+4
[00:44:29] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/Users/douira/Library/Application%20Support/PolyMC/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[00:44:30] [main/INFO]: Compatibility level set to JAVA_16
[00:44:30] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[00:44:30] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[00:44:35] [Render thread/INFO]: [STDERR]: [LWJGL] Platform/architecture mismatch detected for module: org.lwjgl
[00:44:35] [Render thread/INFO]: [STDERR]: 	JVM platform:
[00:44:35] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[00:44:35] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[00:44:35] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[00:44:35] [Render thread/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
		macOS x86_64 17.0.1
		Java HotSpot(TM) 64-Bit Server VM v17.0.1+12-LTS-39 by Oracle Corporation
	Platforms available on classpath:
		linux/x64
		windows/x64
[00:44:36] [Render thread/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463) ~[fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.mojang.blaze3d.systems.RenderSystem
	at net.minecraft.class_6396.method_37123(class_6396.java:65) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_37274(class_310.java:2394) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_22681(class_310.java:2389) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:206) ~[minecraft-1.18.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.7.jar:?]
	... 10 more
Process exited with code 1.
```
I can help with further testing if required! Fabric loader 13.3 didn't fix this.

**Comment by BayuLewis** [comment]
Since Collateral is busy and he could not release new build after new commits you can try this [build](https://drive.google.com/file/d/1NULlSTFwseB3qHjel_IlZBc9xHH09Tj_/view) which I built from the latest [commit](https://github.com/xCollateral/VulkanMod/commit/307a7dad68c934ce335abcc49c592a5f3444836e)

If you get crashed at the first launch, you will need to locate the lib, you need to download [this](https://build.lwjgl.org/release/3.3.1/macosx/arm64/libMoltenVK.dylib) and put it in `/var/folders/lk/b29qxkf10lg8s6616s_2831c0000gn/T/lwjgl[username]/3.3.1-SNAPSHOT`
I hope it will work for you, I tested on my Hackintosh system and it run well.

Remember to use latest Fabric Loader and Minecraft 1.18.2

**Comment by Protoxy22** [comment]
There is no such folder called lwjgl[username]

**Comment by qb20nh** [comment]
graalvm ee gives the similar log output and crashes. ce works fine though.

**Comment by qb20nh** [comment]
firsts line that differs is
[00:44:35] [Render thread/INFO]: [STDERR]: [LWJGL] Platform/architecture mismatch detected for module: org.lwjgl

**Comment by qb20nh** [comment]
~graalvm ee gives the similar log output then crashes. ce works fine though.~
Oracle does not provide arm64 build of ee that's the reason.
<img width="517" alt="image" src="https://user-images.githubusercontent.com/1734074/175852910-ec2af2cb-f06c-4fc1-85ba-a70f0a689b75.png">
<img width="507" alt="image" src="https://user-images.githubusercontent.com/1734074/175852962-5e74845b-c0cf-429d-95ed-cf1a1f0c9c0d.png">

**Comment by AlexanderwithaA** [comment]
I tried your fix, was working until it got to loading textures and is in an infinite fail and reload loop. Lastest build just fails.

**Comment by xCollateral** [comment]
With MacOS specific versions it shouldn't happen anymore.

**Comment by douira** [comment]
> With MacOS specific versions

What do you mean by macOS specific versions? Where can I find these?

**Comment by xCollateral** [comment]
For example here: https://modrinth.com/mod/vulkanmod/version/0.2.0

**Comment by douira** [comment]
ah I see now, thanks
