### ISSUE TITLE
Error on spectator mode (spider view)

### ISSUE THREAD

**Issue by HerrSnorre** [xCollateral/VulkanMod#293]
The game crashes when spectating spiders on the game.

```
[Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.vulkanmod.vulkan.Framebuffer.beginRendering(org.lwjgl.vulkan.VkCommandBuffer, org.lwjgl.system.MemoryStack)" because "framebuffer" is null
	at net.vulkanmod.vulkan.Drawer.beginRendering(Drawer.java:262) ~[VulkanMod_1.19.4-0.3.2.jar:?]
	at net.minecraft.class_276.method_1235(class_276.java:552) ~[client-intermediary.jar:?]
	at net.minecraft.class_283.method_1293(class_283.java:80) ~[client-intermediary.jar:?]
	at net.minecraft.class_279.method_1258(class_279.java:316) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:884) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1218) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[fabric-loader-0.14.22-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: not showing because of my dad
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "net.vulkanmod.vulkan.Framebuffer.beginRendering(org.lwjgl.vulkan.VkCommandBuffer, org.lwjgl.system.MemoryStack)" because "framebuffer" is null
	at net.vulkanmod.vulkan.Drawer.beginRendering(Drawer.java:262)
	at net.minecraft.class_276.method_1235(class_276.java:552)
	at net.minecraft.class_283.method_1293(class_283.java:80)
	at net.minecraft.class_279.method_1258(class_279.java:316)
	at net.minecraft.class_757.method_3192(class_757.java:884)
	at net.minecraft.class_310.method_1523(class_310.java:1218)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.vulkanmod.vulkan.Drawer.beginRendering(Drawer.java:262)
	at net.minecraft.class_276.method_1235(class_276.java:552)
	at net.minecraft.class_283.method_1293(class_283.java:80)
	at net.minecraft.class_279.method_1258(class_279.java:316)

-- Affected level --
Details:
	All players: 1 total; [class_746['notmynickname'/104427, l='ClientLevel', x=-2377.96, y=63.00, z=655.96]]
	Chunk stats: 729, 519
	Level dimension: minecraft:overworld
	Level spawn location: World: (1010,66,-2496), Section: (at 2,2,0 in 63,4,-156; chunk contains blocks 1008,0,-2496 to 1023,255,-2481), Region: (1,-5; contains chunks 32,-160 to 63,-129, blocks 512,0,-2560 to 1023,255,-2049)
	Level time: 181020 game time, 17177169 day time
	Server brand: Vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:825)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Linux (amd64) version 6.4.12-arch1-1
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1889739312 bytes (1802 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: CometLake-H GT2 [UHD Graphics]
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x9bc4
	Graphics card #0 versionInfo: unknown
	Graphics card #1 name: TU117M
	Graphics card #1 vendor: NVIDIA Corporation (0x10de)
	Graphics card #1 VRAM (MB): 288.00
	Graphics card #1 deviceId: 0x1f99
	Graphics card #1 versionInfo: unknown
	Virtual memory max (MB): 7917.03
	Virtual memory used (MB): 9323.48
	Swap memory total (MB): 0.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xmx4G -Xms4G
	Launched Version: fabric-loader-0.14.22-1.19.4
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: 1920x1011
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: pt_pt
	CPU: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
#@!@# Game crashed! Crash report saved to: #@!@# /home/asus/.minecraft/crash-reports/crash-1000-02-31_at_midnight-client.txt
```
I did not try another version, only 1.19.4-0.3.2.
I was using [mangohud](https://github.com/flightlessmango/MangoHud).

In my opinion, its better remove the enderman/spider shaders. Most players dont use does every day.

EDIT 1: Creepers crash the game too, same error.

**Comment by xCollateral** [comment]
Fixed.
