### ISSUE TITLE
crash in world

### ISSUE THREAD

**Issue by jklw10** [xCollateral/VulkanMod#31]
seems random but probably to do with opening F3.

Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:886)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
	at net.minecraft.client.main.Main.main(Main:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'void org.lwjgl.system.Library.loadSystem(java.util.function.Consumer, java.util.function.Consumer, java.lang.Class, java.lang.String)'
	at org.lwjgl.opengl.GL.<clinit>(GL.java:78)
	at org.lwjgl.opengl.GL11.<clinit>(GL11.java:708)
	at com.mojang.blaze3d.platform.GlStateManager$CapabilityTracker.setState(GlStateManager:883)
	at com.mojang.blaze3d.platform.GlStateManager$CapabilityTracker.enable(GlStateManager:875)
	at com.mojang.blaze3d.platform.GlStateManager._enableScissorTest(GlStateManager:56)
	at me.shedaniel.clothconfig2.impl.ScissorsHandlerImpl._applyScissor(ScissorsHandlerImpl.java:118)
	at me.shedaniel.clothconfig2.impl.ScissorsHandlerImpl.applyScissors(ScissorsHandlerImpl.java:108)
	at me.shedaniel.clothconfig2.impl.ScissorsHandlerImpl.scissor(ScissorsHandlerImpl.java:80)
	at me.shedaniel.rei.impl.client.gui.widget.region.EntryStacksRegionWidget.render(EntryStacksRegionWidget.java:124)
	at me.shedaniel.rei.impl.client.gui.widget.favorites.FavoritesListWidget.render(FavoritesListWidget.java:213)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.renderWidgets(ScreenOverlayImpl.java:742)
	at me.shedaniel.rei.impl.client.gui.ScreenOverlayImpl.render(ScreenOverlayImpl.java:641)
	at me.shedaniel.rei.RoughlyEnoughItemsCoreClient.lambda$registerEvents$20(RoughlyEnoughItemsCoreClient.java:396)
	at net.minecraft.client.render.GameRenderer.handler$zda000$renderScreenPost(GameRenderer:3057)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:877)
	
Unhandled game exception
java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.opengl.GL11
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at com.mojang.blaze3d.platform.GlStateManager._blendEquation(GlStateManager:122)
	at com.mojang.blaze3d.systems.RenderSystem.blendEquation(RenderSystem:361)
	at fudge.notenoughcrashes.utils.GlUtil.resetState(GlUtil.java:24)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.resetStates(InGameCatcher.java:41)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:32)
	at net.minecraft.client.MinecraftClient.modify$cao000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:11510)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:759)
	at net.minecraft.client.main.Main.main(Main:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by jklw10** [comment]
![image](https://user-images.githubusercontent.com/8884828/173158567-b74000ab-ccb3-4b72-b3b0-ecded3cd14bf.png)
looks to be something with getting the time? though that blend equation could mean it's entirely not.
could also be a mod incompatability. i'll try with a few less. (flywheel also crashes due to mixins)

**Comment by jklw10** [comment]
seems it was REI (roughly enough resources), and opening the inventory where this crash happened.

**Comment by BayuLewis** [comment]
It's still not compatible with the mod you mentioned above. It tries to modify the rendering which can lead to crash.

**Comment by xCollateral** [comment]
It seems cloth config is making direct gl calls, you should propably contact mod author and ask him to use higher level classes that will redirect to vulkan renderer(such as RenderSystem class).
