### ISSUE TITLE
Crashes on macOS

### ISSUE THREAD

**Issue by iMonZ** [xCollateral/VulkanMod#317]
03:40:38.869
FabricLoader/Mixin
Render thread
Mixin apply for mod iris failed mixins.iris.json:MixinRenderSystem from mod iris -> com.mojang.blaze3d.systems.RenderSystem: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException InjectionPoint(Shift)[@At("INVOKE")] on com/mojang/blaze3d/systems/RenderSystem::_setShaderTexture with priority 1000 cannot inject into com/mojang/blaze3d/systems/RenderSystem::_setShaderTexture(ILnet/minecraft/class_2960;)V merged by net.vulkanmod.mixin.render.RenderSystemMixin with priority 1000 [PREINJECT Applicator Phase -> mixins.iris.json:MixinRenderSystem from mod iris -> Prepare Injections ->  -> handler$chd000$iris$_setShaderTexture(ILnet/minecraft/class_2960;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_1060;Lnet/minecraft/class_1044;)V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on com/mojang/blaze3d/systems/RenderSystem::_setShaderTexture with priority 1000 cannot inject into com/mojang/blaze3d/systems/RenderSystem::_setShaderTexture(ILnet/minecraft/class_2960;)V merged by net.vulkanmod.mixin.render.RenderSystemMixin with priority 1000 [PREINJECT Applicator Phase -> mixins.iris.json:MixinRenderSystem from mod iris -> Prepare Injections ->  -> handler$chd000$iris$_setShaderTexture(ILnet/minecraft/class_2960;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_1060;Lnet/minecraft/class_1044;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.minecraft.class_310.method_37274(class_310.java:2500)
	at net.minecraft.class_310.method_22681(class_310.java:2494)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
03:40:38.870
FabricLoader
Render thread
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of com.mojang.blaze3d.systems.RenderSystem failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of com.mojang.blaze3d.systems.RenderSystem failed
	at net.minecraft.class_310.method_37274(class_310.java:2500)
	at net.minecraft.class_310.method_22681(class_310.java:2494)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of com.mojang.blaze3d.systems.RenderSystem failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 10 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.iris.json:MixinRenderSystem from mod iris] from phase [DEFAULT] in config [mixins.iris.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 13 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: InjectionPoint(Shift)[@At("INVOKE")] on com/mojang/blaze3d/systems/RenderSystem::_setShaderTexture with priority 1000 cannot inject into com/mojang/blaze3d/systems/RenderSystem::_setShaderTexture(ILnet/minecraft/class_2960;)V merged by net.vulkanmod.mixin.render.RenderSystemMixin with priority 1000 [PREINJECT Applicator Phase -> mixins.iris.json:MixinRenderSystem from mod iris -> Prepare Injections ->  -> handler$chd000$iris$_setShaderTexture(ILnet/minecraft/class_2960;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_1060;Lnet/minecraft/class_1044;)V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 13 more
03:40:38.904
launcher
main

03:40:38.904
monitor
Process Monitor
Process crashed with exit code 1

**Comment by iMonZ** [comment]
03:43:26.673
FabricLoader/Mixin
Render thread
@Final field field_22786:Ljava/util/List; in mixins.ipnext.json:MixinScreen from mod inventoryprofilesnext should be final
03:43:26.677
FabricLoader/Mixin
Render thread
@Final field field_33815:Ljava/util/List; in mixins.ipnext.json:MixinScreen from mod inventoryprofilesnext should be final
03:43:26.687
FabricLoader/Mixin
Render thread
Mixing client.MixinTitleScreen from mixins/common/nochatreports.mixins.json into net.minecraft.class_442
03:43:26.704
FabricLoader/Mixin
Render thread
Mixing client.MixinChatScreen from mixins/common/nochatreports.mixins.json into net.minecraft.class_408
03:43:26.704
FabricLoader/Mixin
Render thread
Renaming synthetic method lambda$onInit$4()Lnet/minecraft/class_2561; to mdddd882$nochatreports$lambda$onInit$4$1 in mixins/common/nochatreports.mixins.json:client.MixinChatScreen from mod nochatreports
03:43:26.704
FabricLoader/Mixin
Render thread
Renaming synthetic method lambda$onInit$3(Lnet/minecraft/class_4185;)V to mdddd882$nochatreports$lambda$onInit$3$2 in mixins/common/nochatreports.mixins.json:client.MixinChatScreen from mod nochatreports
03:43:26.704
FabricLoader/Mixin
Render thread
Renaming synthetic method lambda$onInit$2()Lnet/minecraft/class_2561; to mdddd882$nochatreports$lambda$onInit$2$3 in mixins/common/nochatreports.mixins.json:client.MixinChatScreen from mod nochatreports
03:43:26.704
FabricLoader/Mixin
Render thread
Renaming synthetic method lambda$onInit$1(Lnet/minecraft/class_4185;)V to mdddd882$nochatreports$lambda$onInit$1$4 in mixins/common/nochatreports.mixins.json:client.MixinChatScreen from mod nochatreports
03:43:26.704
FabricLoader/Mixin
Render thread
Renaming synthetic method lambda$onBeforeMessage$0(Ljava/lang/String;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfoReturnable;Lcom/aizistral/nochatreports/common/encryption/Encryptor;)V to mdddd882$nochatreports$lambda$onBeforeMessage$0$5 in mixins/common/nochatreports.mixins.json:client.MixinChatScreen from mod nochatreports
03:43:26.747
FabricLoader/Mixin
Render thread
Instancing error handler class dev.isxander.debugify.mixinplugin.DebugifyErrorHandler
03:43:26.747
FabricLoader/Mixin
Render thread
Mixin apply for mod sodium failed sodium.mixins.json:workarounds.event_loop.RenderSystemMixin from mod sodium -> com.mojang.blaze3d.systems.RenderSystem: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("INVOKE") on com/mojang/blaze3d/systems/RenderSystem::removeFirstPoll with priority 1000 cannot inject into com/mojang/blaze3d/systems/RenderSystem::flipFrame(J)V merged by net.vulkanmod.mixin.render.RenderSystemMixin with priority 1000 [PREINJECT Applicator Phase -> sodium.mixins.json:workarounds.event_loop.RenderSystemMixin from mod sodium -> Prepare Injections ->  -> redirect$dhi000$sodium$removeFirstPoll()V -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on com/mojang/blaze3d/systems/RenderSystem::removeFirstPoll with priority 1000 cannot inject into com/mojang/blaze3d/systems/RenderSystem::flipFrame(J)V merged by net.vulkanmod.mixin.render.RenderSystemMixin with priority 1000 [PREINJECT Applicator Phase -> sodium.mixins.json:workarounds.event_loop.RenderSystemMixin from mod sodium -> Prepare Injections ->  -> redirect$dhi000$sodium$removeFirstPoll()V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.minecraft.class_310.method_37274(class_310.java:2500)
	at net.minecraft.class_310.method_22681(class_310.java:2494)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
03:43:26.748
FabricLoader
Render thread
Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of com.mojang.blaze3d.systems.RenderSystem failed
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of com.mojang.blaze3d.systems.RenderSystem failed
	at net.minecraft.class_310.method_37274(class_310.java:2500)
	at net.minecraft.class_310.method_22681(class_310.java:2494)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of com.mojang.blaze3d.systems.RenderSystem failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 6 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 10 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [sodium.mixins.json:workarounds.event_loop.RenderSystemMixin from mod sodium] from phase [DEFAULT] in config [sodium.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 13 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on com/mojang/blaze3d/systems/RenderSystem::removeFirstPoll with priority 1000 cannot inject into com/mojang/blaze3d/systems/RenderSystem::flipFrame(J)V merged by net.vulkanmod.mixin.render.RenderSystemMixin with priority 1000 [PREINJECT Applicator Phase -> sodium.mixins.json:workarounds.event_loop.RenderSystemMixin from mod sodium -> Prepare Injections ->  -> redirect$dhi000$sodium$removeFirstPoll()V -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305)
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 13 more
03:43:26.779
launcher
main

**Comment by iMonZ** [comment]
Maybe the MoltenVK library is missing?

**Comment by iMonZ** [comment]
Okay so it works with Vanilla+Fabric, but it doesn't work with Fabric+Iris+Sodium

**Comment by Zorklis** [comment]
Yeah duh, they are incompatible.
This should be closed.
