### ISSUE TITLE
Cannot launch on Linux - no context is current or available

### ISSUE THREAD

**Issue by isXander** [xCollateral/VulkanMod#32]
This is probably covered under `Linux or MacOS may not work` in the README but here is a tracking issue nonetheless. 

```
FATAL ERROR in native method: Thread[Render thread,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL11C.glBindTexture(Native Method)
	at org.lwjgl.opengl.GL11.glBindTexture(GL11.java:854)
	at com.mojang.blaze3d.platform.GlStateManager._bindTexture(GlStateManager.java:565)
	at com.mojang.blaze3d.platform.TextureUtil.bind(TextureUtil.java:83)
	at com.mojang.blaze3d.platform.TextureUtil.prepareImage(TextureUtil.java:69)
	at com.mojang.blaze3d.platform.TextureUtil.prepareImage(TextureUtil.java:56)
	at net.minecraft.client.texture.NativeImageBackedTexture.<init>(NativeImageBackedTexture.java:40)
	at net.minecraft.client.render.OverlayTexture.<init>(OverlayTexture.java:24)
	at net.minecraft.client.render.GameRenderer.<init>(GameRenderer.java:252)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:583)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.lang.invoke.LambdaForm$DMH/0x0000000800eb4000.invokeStaticInit(java.base@17.0.3/LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/0x0000000800cdc000.invokeExact_MT(java.base@17.0.3/LambdaForm$MH)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.lang.invoke.LambdaForm$DMH/0x0000000800c02800.invokeStatic(java.base@17.0.3/LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/0x0000000800cdc000.invokeExact_MT(java.base@17.0.3/LambdaForm$MH)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
	at java.lang.invoke.LambdaForm$DMH/0x0000000800c02800.invokeStatic(java.base@17.0.3/LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/0x0000000800cdc000.invokeExact_MT(java.base@17.0.3/LambdaForm$MH)
	at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:217)
```

Note that this crash is in a development environment.

**Comment by LegacyGamerHD** [comment]
it works on android :P

**Comment by isXander** [comment]
In that case I will specify the distro:
Arch Linux (nvidia-open-dkms drivers)

**Comment by xCollateral** [comment]
It seems your instance is trying to call gl functions, are you testing with other mods? If so remove them and test again.
Also fabulous graphics is not supported.

**Comment by isXander** [comment]
Only other mod is debugify, which I am actively trying to get support vulkanmod. Note debugify doesn't modify anything to do with texture loading.

**Comment by RoccoDev** [comment]
It's working for me. (NVIDIA proprietary, Fedora GNU/Linux, no mods)

![immagine](https://user-images.githubusercontent.com/13873938/174493704-f6aa7865-4afe-4bcc-b48b-51bebd92a2ed.png)

**Comment by JustCryen** [comment]
> In that case I will specify the distro: Arch Linux (nvidia-open-dkms drivers)

Whatt is the `nvidia-open-dkms` package? nouveau drivers?
I'm using the `nvidia-dkms` and I have an error on startup (Process exited with code 255)

**Comment by polarbub** [comment]
`Nouveau` is the foss drivers made by xorg. It doesn't support ampere cards. It's slower than the other two options because it doesn't do power management. 

`nvidia` is the proprietary driver made by nvidia. It supports all the cards. Some older cards require the 390.xx or 340.xx driver branches from the aur.is the prebuilt kernel drivers for some older kernels.

`nvidia-dkms` replaces nvidia builds the kernel interface for your kernel. This allows for non-standard kernels or ones that nvidia doesn't ship pre build interfaces for to be used. Most people on arch should use this.

`nvidia-dkms-open` is nvidia's open sourced kernel drivers for turing and ampere cards. The rest of the driver is still proprietary though.

**Comment by polarbub** [comment]
Also please send the whole error log

**Comment by JustCryen** [comment]
Ohh, so the opensourced (partially) drivers are a separate package, alright, thanks!
There's a log with only this mod enabled (mc 1.19.0)
```
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 7/3/22, 8:39 PM
Description: Initializing game

java.lang.IndexOutOfBoundsException
	at org.lwjgl.system.StructBuffer.check(StructBuffer.java:311)
	at org.lwjgl.system.StructBuffer.get(StructBuffer.java:90)
	at net.vulkanmod.vulkan.Vulkan.findQueueFamilies(Vulkan.java:1037)
	at net.vulkanmod.vulkan.Vulkan.isDeviceSuitable(Vulkan.java:951)
	at net.vulkanmod.vulkan.Vulkan.pickPhysicalDevice(Vulkan.java:362)
	at net.vulkanmod.vulkan.Vulkan.initVulkan(Vulkan.java:182)
	at net.vulkanmod.vulkan.VRenderSystem.initRenderer(VRenderSystem.java:59)
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:1510)
	at net.minecraft.class_310.<init>(class_310.java:492)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.lwjgl.system.StructBuffer.check(StructBuffer.java:311)
	at org.lwjgl.system.StructBuffer.get(StructBuffer.java:90)
	at net.vulkanmod.vulkan.Vulkan.findQueueFamilies(Vulkan.java:1037)
	at net.vulkanmod.vulkan.Vulkan.isDeviceSuitable(Vulkan.java:951)
	at net.vulkanmod.vulkan.Vulkan.pickPhysicalDevice(Vulkan.java:362)
	at net.vulkanmod.vulkan.Vulkan.initVulkan(Vulkan.java:182)
	at net.vulkanmod.vulkan.VRenderSystem.initRenderer(VRenderSystem.java:59)
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:1510)
	at net.minecraft.class_310.<init>(class_310.java:492)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Linux (amd64) version 5.18.8-zen1-1-zen
	Java Version: 18.0.1.1, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2317640576 bytes (2210 MiB) / 3138387968 bytes (2993 MiB) up to 8431075328 bytes (8040 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: unknown
	Frequency (GHz): 2.20
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: CoffeeLake-H GT2 [UHD Graphics 630]
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x3e9b
	Graphics card #0 versionInfo: unknown
	Graphics card #1 name: GP106M [GeForce GTX 1060 Mobile]
	Graphics card #1 vendor: NVIDIA Corporation (0x10de)
	Graphics card #1 VRAM (MB): 288.00
	Graphics card #1 deviceId: 0x1c20
	Graphics card #1 versionInfo: unknown
	Virtual memory max (MB): 40666.14
	Virtual memory used (MB): 7526.61
	Swap memory total (MB): 32768.00
	Swap memory used (MB): 0.00
	JVM Flags: 8 total; -XX:+DisableExplicitGC -XX:MaxGCPauseMillis=500 -XX:SurvivorRatio=16 -XX:+UseParallelGC -XX:UseSSE=3 -XX:ParallelGCThreads=12 -Xms192m -Xmx8192m
	Launched Version: 1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
```

**Comment by isXander** [comment]
Unrelated crash

**Comment by JustCryen** [comment]
Should I open a new issue then?
I don't see a similar one posted already.

**Comment by nonetrix** [comment]
> > In that case I will specify the distro: Arch Linux (nvidia-open-dkms drivers)
> 
> Whatt is the `nvidia-open-dkms` package? nouveau drivers? I'm using the `nvidia-dkms` and I have an error on startup (Process exited with code 255)

No they recently open sourced the drivers only thing is proprietary now I think is user space OpenGL and Vulkan drivers etc
