### ISSUE TITLE
Swap chain issues still exist 

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [xCollateral/VulkanMod#324]
Just wanted to let you know that frames are still presented in the wrong order when minImageCount >2 ~~and that this project still causes GPU resets on RADV~~ fixed when retesting on mesa 24-git. out of order presentation is still an issue, but we are getting over 500 fps at 1080p fullscreen (32 chunks), which is very impressive and also mostly eliminates the issue due to the large number of frames being rendered. Best method to reproduce on my machine is to set fps limiter to 30 in fullscreen mode. 

Thanks

**Comment by Borketh** [comment]
```
Time: 2023-12-09 05:28:14
Description: Initializing game

java.lang.RuntimeException: Failed to create swap chain
	at net.vulkanmod.vulkan.framebuffer.SwapChain.createSwapChain(SwapChain.java:144)
	at net.vulkanmod.vulkan.framebuffer.SwapChain.<init>(SwapChain.java:60)
	at net.vulkanmod.vulkan.Vulkan.createSwapChain(Vulkan.java:169)
	at net.vulkanmod.vulkan.Vulkan.initVulkan(Vulkan.java:151)
	at net.vulkanmod.vulkan.VRenderSystem.initRenderer(VRenderSystem.java:58)
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:1516)
	at net.minecraft.class_310.<init>(class_310.java:513)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.vulkanmod.vulkan.framebuffer.SwapChain.createSwapChain(SwapChain.java:144)
	at net.vulkanmod.vulkan.framebuffer.SwapChain.<init>(SwapChain.java:60)
	at net.vulkanmod.vulkan.Vulkan.createSwapChain(Vulkan.java:169)
	at net.vulkanmod.vulkan.Vulkan.initVulkan(Vulkan.java:151)
	at net.vulkanmod.vulkan.VRenderSystem.initRenderer(VRenderSystem.java:58)
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:1516)
	at net.minecraft.class_310.<init>(class_310.java:513)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Linux (amd64) version 6.6.4-zen1-1-zen
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 543719480 bytes (518 MiB) / 671088640 bytes (640 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: TigerLake-H GT1 [UHD Graphics]
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x9a68
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 47719.37
	Virtual memory used (MB): 7944.21
	Swap memory total (MB): 31820.00
	Swap memory used (MB): 0.00
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	JVM uptime in seconds: 7.107
	Launched Version: fabric-loader-0.15.1-1.20.2
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Locale: en_CA
	CPU: 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
```

**Comment by xCollateral** [comment]
It should be solved now.
