### ISSUE TITLE
[Crash] Doesn't launch on Nouveau drivers

### ISSUE THREAD

**Issue by TheoCGaming** [xCollateral/VulkanMod#330]
# System Information

- OS: Arch Linux (6.6.1-zen1-1-zen)
- GPU: NVIDIA GeForce GTX 1650 Super (nouveau 1.0.17-2 drivers)
- Java Version: 17
- Launcher: Prism
- DE: KDE
- Loader: Fabric
- Mods Present: Fabric API, VulkanMod (these are the only 2 present as far as I'm aware.)

# Log
```
Prism Launcher version: 7.2 (archlinux)


Launched instance in online mode

authserver.mojang.com resolves to:
    [18.161.6.124, 18.161.6.111, 18.161.6.107, 18.161.6.63]

session.minecraft.net resolves to:
    [2620:1ec:bdf::70, 2620:1ec:46::70, 13.107.246.70, 13.107.213.70]

textures.minecraft.net resolves to:
    [2620:1ec:46::70, 2620:1ec:bdf::70, 13.107.213.70, 13.107.246.70]

api.mojang.com resolves to:
    [2620:1ec:46::70, 2620:1ec:bdf::70, 13.107.213.70, 13.107.246.70]


Minecraft folder is:
/home/theocgaming/.local/share/PrismLauncher/instances/1.20.2/.minecraft


Java path is:
/usr/lib/jvm/java-17-openjdk/bin/java


Java is version 17.0.9, using 64 (amd64) architecture, from N/A.


Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
NVIDIA Corporation TU116 [GeForce GTX 1650 SUPER] (rev a1)

Subsystem: eVga.com. Corp. TU116 [GeForce GTX 1650 SUPER]

Kernel driver in use: nouveau

OpenGL version string: 4.3 (Compatibility Profile) Mesa 23.2.1-arch1.2

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  /home/theocgaming/.local/share/PrismLauncher/instances/1.20.2/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS
```
<summary>Libraries: </summary>

<details>  
<ul>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-linux/3.3.2/lwjgl-glfw-natives-linux-3.3.2.jar</li>
<li>  /home/theocgaming/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-linux/3.3.2/lwjgl-jemalloc-natives-linux-3.3.2.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-natives-linux/3.3.2/lwjgl-natives-linux-3.3.2.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-openal-natives-linux/3.3.2/lwjgl-openal-natives-linux-3.3.2.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl-natives-linux/3.3.2/lwjgl-opengl-natives-linux-3.3.2.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-stb-natives-linux/3.3.2/lwjgl-stb-natives-linux-3.3.2.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd-natives-linux/3.3.2/lwjgl-tinyfd-natives-linux-3.3.2.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/com/github/oshi/oshi-core/6.4.5/oshi-core-6.4.5.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/com/google/guava/guava/32.1.2-jre/guava-32.1.2-jre.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/com/ibm/icu/icu4j/73.2/icu4j-73.2.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/com/mojang/authlib/5.0.47/authlib-5.0.47.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/commons-codec/commons-codec/1.16.0/commons-codec-1.16.0.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/commons-io/commons-io/2.13.0/commons-io-2.13.0.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/io/netty/netty-buffer/4.1.97.Final/netty-buffer-4.1.97.Final.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/io/netty/netty-codec/4.1.97.Final/netty-codec-4.1.97.Final.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/io/netty/netty-common/4.1.97.Final/netty-common-4.1.97.Final.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/io/netty/netty-handler/4.1.97.Final/netty-handler-4.1.97.Final.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/io/netty/netty-resolver/4.1.97.Final/netty-resolver-4.1.97.Final.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/io/netty/netty-transport-classes-epoll/4.1.97.Final/netty-transport-classes-epoll-4.1.97.Final.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/io/netty/netty-transport-native-epoll/4.1.97.Final/netty-transport-native-epoll-4.1.97.Final-linux-aarch_64.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/io/netty/netty-transport-native-epoll/4.1.97.Final/netty-transport-native-epoll-4.1.97.Final-linux-x86_64.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/io/netty/netty-transport-native-unix-common/4.1.97.Final/netty-transport-native-unix-common-4.1.97.Final.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/io/netty/netty-transport/4.1.97.Final/netty-transport-4.1.97.Final.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/it/unimi/dsi/fastutil/8.5.12/fastutil-8.5.12.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/net/java/dev/jna/jna-platform/5.13.0/jna-platform-5.13.0.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/net/java/dev/jna/jna/5.13.0/jna-5.13.0.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/apache/commons/commons-compress/1.22/commons-compress-1.22.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.13.0/commons-lang3-3.13.0.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.4.16/httpcore-4.4.16.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/slf4j/slf4j-api/2.0.7/slf4j-api-2.0.7.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/net/fabricmc/intermediary/1.20.2/intermediary-1.20.2.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/ow2/asm/asm/9.5/asm-9.5.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/ow2/asm/asm-analysis/9.5/asm-analysis-9.5.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/ow2/asm/asm-commons/9.5/asm-commons-9.5.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/ow2/asm/asm-tree/9.5/asm-tree-9.5.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/org/ow2/asm/asm-util/9.5/asm-util-9.5.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/net/fabricmc/fabric-loader/0.14.22/fabric-loader-0.14.22.jar</li>
<li>/home/theocgaming/.local/share/PrismLauncher/libraries/com/mojang/minecraft/1.20.2/minecraft-1.20.2-client.jar</li>
</ul>

</details>

```

Native libraries:

Mods:
  [✔] fabric-api-0.90.7+1.20.2
  [✔] VulkanMod_1.20.2-0.3.5

Params:
  --username  --version 1.20.2 --gameDir /home/theocgaming/.local/share/PrismLauncher/instances/1.20.2/.minecraft --assetsDir /home/theocgaming/.local/share/PrismLauncher/assets --assetIndex 8 --uuid  --accessToken  --userType  --versionType release

Window size: 1280 x 720

Launcher: standard

Java Arguments:
[-Xms512m, -Xmx6144m, -Duser.language=en]


Minecraft process ID: 94439


[08:51:25] [main/INFO]: Loading Minecraft 1.20.2 with Fabric Loader 0.14.22
```
<summary> [08:51:25] [main/INFO]: Loading 67 mods: </summary>
	<details>
<ul>

<li>- fabric-api 0.90.7+1.20.2 </li>

<li>	   |-- fabric-api-base 0.4.33+fce67b32a0</li>
<li>	   |-- fabric-api-lookup-api-v1 1.6.42+b1792f7da0</li>
<li>	   |-- fabric-biome-api-v1 13.0.14+b1792f7da0</li>
<li>	   |-- fabric-block-api-v1 1.0.12+73761d2ea0</li>
<li>	   |-- fabric-block-view-api-v2 1.0.1+73761d2ea0</li>
<li>	   |-- fabric-blockrenderlayer-v1 1.1.43+f4b7e424a0</li>
<li>	   |-- fabric-client-tags-api-v1 1.1.4+86b12645a0</li>
<li>	   |-- fabric-command-api-v1 1.2.37+f71b366fa0</li>
<li>	   |-- fabric-command-api-v2 2.2.16+b1792f7da0</li>
<li>	   |-- fabric-commands-v0 0.2.54+df3654b3a0</li>
<li>	   |-- fabric-containers-v0 0.1.75+df3654b3a0</li>
<li>	   |-- fabric-content-registries-v0 5.0.5+b1792f7da0</li>
<li>	   |-- fabric-convention-tags-v1 1.5.8+b1792f7da0</li>
<li>	   |-- fabric-crash-report-info-v1 0.2.20+f4b7e424a0</li>
<li>	   |-- fabric-data-generation-api-v1 13.1.5+b1792f7da0</li>
<li>	   |-- fabric-dimensions-v1 2.1.57+b1792f7da0</li>
<li>	   |-- fabric-entity-events-v1 1.5.26+b1792f7da0</li>
<li>	   |-- fabric-events-interaction-v0 0.6.10+b1792f7da0</li>
<li>	   |-- fabric-events-lifecycle-v0 0.2.69+df3654b3a0</li>
<li>	   |-- fabric-game-rule-api-v1 1.0.42+a44e16a6a0</li>
<li>	   |-- fabric-item-api-v1 2.1.33+b1792f7da0</li>
<li>	   |-- fabric-item-group-api-v1 4.0.15+e3d2bf3fa0</li>
<li>	   |-- fabric-key-binding-api-v1 1.0.38+f4b7e424a0</li>
<li>	   |-- fabric-keybindings-v0 0.2.36+df3654b3a0</li>
<li>	   |-- fabric-lifecycle-events-v1 2.2.27+b1792f7da0</li>
<li>	   |-- fabric-loot-api-v2 2.1.1+3ba460fba0</li>
<li>	   |-- fabric-message-api-v1 6.0.2+e3d2bf3fa0</li>
<li>	   |-- fabric-mining-level-api-v1 2.1.55+f4b7e424a0</li>
<li>	   |-- fabric-model-loading-api-v1 1.0.6+b1792f7da0</li>
<li>	   |-- fabric-models-v0 0.4.5+9386d8a7a0</li>
<li>	   |-- fabric-networking-api-v1 3.0.11+bff13c85a0</li>
<li>	   |-- fabric-object-builder-api-v1 12.1.2+2ff98d3ba0</li>
<li>	   |-- fabric-particles-v1 1.1.4+f4b7e424a0</li>
<li>	   |-- fabric-recipe-api-v1 2.0.8+52b3ebe5a0</li>
<li>	   |-- fabric-registry-sync-v0 4.0.6+b1792f7da0</li>
<li>	   |-- fabric-renderer-api-v1 3.2.1+2034447ca0</li>
<li>	   |-- fabric-renderer-indigo 1.5.1+2034447ca0</li>
<li>	   |-- fabric-renderer-registries-v1 3.2.49+df3654b3a0</li>
<li>	   |-- fabric-rendering-data-attachment-v1 0.3.39+73761d2ea0</li>
<li>	   |-- fabric-rendering-fluids-v1 3.0.30+f4b7e424a0</li>
<li>	   |-- fabric-rendering-v0 1.1.52+df3654b3a0</li>
<li>	   |-- fabric-rendering-v1 3.0.11+b1792f7da0</li>
<li>	   |-- fabric-resource-conditions-api-v1 2.3.10+e3d2bf3fa0</li>
<li>	   |-- fabric-resource-loader-v0 0.11.12+b1792f7da0</li>
<li>	   |-- fabric-screen-api-v1 2.0.12+b1792f7da0</li>
<li>	   |-- fabric-screen-handler-api-v1 1.3.41+b1792f7da0</li>
<li>	   |-- fabric-sound-api-v1 1.0.14+f4b7e424a0</li>
<li>	   |-- fabric-transfer-api-v1 3.3.10+bb1ee60ea0</li>
<li>	   \-- fabric-transitive-access-wideners-v1 5.0.3+fce67b32a0</li>
<li>	- fabricloader 0.14.22</li>
<li>	- java 17</li>
<li>	- minecraft 1.20.2</li>
<li>	- vulkanmod 0.3.5</li>
<li>	   |-- org_lwjgl_lwjgl-shaderc 3.3.2</li>
<li>	   |-- org_lwjgl_lwjgl-shaderc_natives-linux 3.3.2</li>
<li>	   |-- org_lwjgl_lwjgl-shaderc_natives-macos 3.3.2</li>
<li>	   |-- org_lwjgl_lwjgl-shaderc_natives-macos-arm64 3.3.2</li>
<li>	   |-- org_lwjgl_lwjgl-shaderc_natives-windows 3.3.2</li>
<li>	   |-- org_lwjgl_lwjgl-vma 3.3.2</li>
<li>	   |-- org_lwjgl_lwjgl-vma_natives-linux 3.3.2</li>
<li>	   |-- org_lwjgl_lwjgl-vma_natives-macos 3.3.2</li>
<li>	   |-- org_lwjgl_lwjgl-vma_natives-macos-arm64 3.3.2</li>
<li>	   |-- org_lwjgl_lwjgl-vma_natives-windows 3.3.2</li>
<li>	   |-- org_lwjgl_lwjgl-vulkan 3.3.2</li>
<li>	   |-- org_lwjgl_lwjgl-vulkan_natives-macos 3.3.2</li>
<li>	   \-- org_lwjgl_lwjgl-vulkan_natives-macos-arm64 3.3.2 </li>
</ul>
</details>

```

[08:51:25] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/theocgaming/.local/share/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[08:51:25] [main/INFO]: Compatibility level set to JAVA_16
[08:51:25] [main/INFO]: Compatibility level set to JAVA_17
[08:51:31] [Datafixer Bootstrap/INFO]: 192 Datafixer optimizations took 134 milliseconds
[08:51:33] [Render thread/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[08:51:33] [Render thread/INFO]: Setting user: TheoCGaming
[08:51:33] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[08:51:33] [Render thread/INFO]: == VulkanMod ==
[08:51:34] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!
Time: 2023-11-21 08:51:34
Description: Initializing game
java.lang.RuntimeException: Failed to create instance
	at net.vulkanmod.vulkan.Vulkan.createInstance(Vulkan.java:261)
	at net.vulkanmod.vulkan.Vulkan.initVulkan(Vulkan.java:138)
	at net.vulkanmod.vulkan.VRenderSystem.initRenderer(VRenderSystem.java:58)
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:1516)
	at net.minecraft.class_310.<init>(class_310.java:513)
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at net.vulkanmod.vulkan.Vulkan.createInstance(Vulkan.java:261)
	at net.vulkanmod.vulkan.Vulkan.initVulkan(Vulkan.java:138)
	at net.vulkanmod.vulkan.VRenderSystem.initRenderer(VRenderSystem.java:58)
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:1516)
	at net.minecraft.class_310.<init>(class_310.java:513)
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:214)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Linux (amd64) version 6.6.1-zen1-1-zen
	Java Version: 17.0.9, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 180789248 bytes (172 MiB) / 603979776 bytes (576 MiB) up to 6442450944 bytes (6144 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
	Identifier: Intel64 Family 6 Model 63 Stepping 2
	Microarchitecture: Haswell (Server)
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: TU116 [GeForce GTX 1650 SUPER]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x2187
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 32394.43
	Virtual memory used (MB): 13861.21
	Swap memory total (MB): 16383.99
	Swap memory used (MB): 11.75
	JVM Flags: 2 total; -Xms512m -Xmx6144m
```
<summary>Fabric Mods: </summary>
<details>
<code>
		fabric-api: Fabric API 0.90.7+1.20.2
			fabric-api-base: Fabric API Base 0.4.33+fce67b32a0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.42+b1792f7da0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.14+b1792f7da0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.12+73761d2ea0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+73761d2ea0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.43+f4b7e424a0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.4+86b12645a0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.37+f71b366fa0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.16+b1792f7da0
			fabric-commands-v0: Fabric Commands (v0) 0.2.54+df3654b3a0
			fabric-containers-v0: Fabric Containers (v0) 0.1.75+df3654b3a0
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.5+b1792f7da0
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.8+b1792f7da0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.20+f4b7e424a0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.1.5+b1792f7da0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.57+b1792f7da0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.26+b1792f7da0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.10+b1792f7da0
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.69+df3654b3a0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.42+a44e16a6a0
			fabric-item-api-v1: Fabric Item API (v1) 2.1.33+b1792f7da0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.15+e3d2bf3fa0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.38+f4b7e424a0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.36+df3654b3a0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.27+b1792f7da0
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.1+3ba460fba0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.2+e3d2bf3fa0
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.55+f4b7e424a0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.6+b1792f7da0
			fabric-models-v0: Fabric Models (v0) 0.4.5+9386d8a7a0
			fabric-networking-api-v1: Fabric Networking API (v1) 3.0.11+bff13c85a0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 12.1.2+2ff98d3ba0
			fabric-particles-v1: Fabric Particles (v1) 1.1.4+f4b7e424a0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.8+52b3ebe5a0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.6+b1792f7da0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+2034447ca0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.1+2034447ca0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.49+df3654b3a0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.39+73761d2ea0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.30+f4b7e424a0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.52+df3654b3a0
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.11+b1792f7da0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.10+e3d2bf3fa0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.12+b1792f7da0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.12+b1792f7da0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.41+b1792f7da0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.14+f4b7e424a0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.10+bb1ee60ea0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.3+fce67b32a0
		fabricloader: Fabric Loader 0.14.22
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.2
		vulkanmod: VulkanMod 0.3.5
			org_lwjgl_lwjgl-shaderc: lwjgl-shaderc 3.3.2
			org_lwjgl_lwjgl-shaderc_natives-linux: lwjgl-shaderc 3.3.2
			org_lwjgl_lwjgl-shaderc_natives-macos: lwjgl-shaderc 3.3.2
			org_lwjgl_lwjgl-shaderc_natives-macos-arm64: lwjgl-shaderc 3.3.2
			org_lwjgl_lwjgl-shaderc_natives-windows: lwjgl-shaderc 3.3.2
			org_lwjgl_lwjgl-vma: lwjgl-vma 3.3.2
			org_lwjgl_lwjgl-vma_natives-linux: lwjgl-vma 3.3.2
			org_lwjgl_lwjgl-vma_natives-macos: lwjgl-vma 3.3.2
			org_lwjgl_lwjgl-vma_natives-macos-arm64: lwjgl-vma 3.3.2
			org_lwjgl_lwjgl-vma_natives-windows: lwjgl-vma 3.3.2
			org_lwjgl_lwjgl-vulkan: lwjgl-vulkan 3.3.2
			org_lwjgl_lwjgl-vulkan_natives-macos: lwjgl-vulkan 3.3.2
			org_lwjgl_lwjgl-vulkan_natives-macos-arm64: lwjgl-vulkan 3.3.2
</code>
</details>

```
	JVM uptime in seconds: 10.657
	Launched Version: 1.20.2
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Locale: en_US
	CPU: Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz
#@!@# Game crashed! Crash report saved to: #@!@# /home/theocgaming/.local/share/PrismLauncher/instances/1.20.2/.minecraft/crash-reports/crash-2023-11-21_08.51.34-client.txt
Process exited with code 255.
Clipboard copy at: 21 Nov 2023 08:52:27 -0800
```

**Comment by TheoCGaming** [comment]
hAAAH github flavored markdown is an unmaintained mess

**Comment by JL2210** [comment]
Doesn't NVK only support Vulkan 1.0?
To be blunt, why are you trying to game on Nouveau anyway? Last time I tried it it was unusable even for basic tasks.

**Comment by TheoCGaming** [comment]
> Doesn't NVK only support Vulkan 1.0? To be blunt, why are you trying to game on Nouveau anyway? Last time I tried it it was unusable even for basic tasks.

Because proprietary drivers are unusable on Wayland due to a regression in thr latest drivers.

**Comment by HunterCZ122** [comment]
Seems to work fine on NVK.

![2024-01-17_20 47 20](https://github.com/xCollateral/VulkanMod/assets/23011428/dd5c8be0-03bf-4fb3-9c29-48788de07d82)

You may need to force Vulkan version to 1.3: `MESA_VK_VERSION_OVERRIDE=1.3`
EDIT: Also currently you need to compile NVK yourself to make it work since not a single distro compiles Mesa with NVK.
EDIT2: [NVK now advertises Vulkan 1.3,](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/27317) so no need to force Vulkan version anymore.

**Comment by gfififid** [comment]
Now in arch(and others with AUR) you don't need to compile nvk yourself. You need: kernel 6.7 and 2 AUR packeges: vulkan-nouveau-git and lib32-vulkan-nouveau-git. I'm using Manjaro (6.7.0-0-MANJARO) with RTX 4060
![image](https://github.com/xCollateral/VulkanMod/assets/62612037/3dad4f4f-fcea-4f02-93e8-f3706a7d9bec)

**Comment by HunterCZ122** [comment]
Most rolling release distros now ship NVK and work fine with VulkanMod, so this issue should be closed.

**Comment by Versatile-One** [comment]
@TheoCGaming This can be closed now
