### ISSUE TITLE
F3+S does not dump texture atlas/occasionally crashes

### ISSUE THREAD

**Issue by JL2210** [xCollateral/VulkanMod#335]
While I was debugging #330 I tried to dump the texture atlas with F3+S. With other mods installed it just dumped a screenshot of my current world in varying sizes. When I did it in a standalone instance (just VulkanMod), the game locked up my computer for a few seconds and crashed. Relevant log:

```
[21:57:39] [Render thread/INFO]: [System] [CHAT] [Debug]: Saved dynamic textures to screenshots\debug
[21:57:39] [Render thread/ERROR]: Unreported exception thrown!
java.lang.RuntimeException: Failed to submit draw command buffer: -4
	at net.vulkanmod.vulkan.Renderer.submitFrame(Renderer.java:356) ~[VulkanMod_1.20.2-0.3.6.jar:?]
	at net.vulkanmod.vulkan.Renderer.endFrame(Renderer.java:259) ~[VulkanMod_1.20.2-0.3.6.jar:?]
	at net.minecraft.class_310.handler$zzm000$vulkanmod$submitRender(class_310.java:3118) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1297) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[minecraft-1.20.2-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.0.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
```

**Comment by Versatile-One** [comment]
@JL2210 This can be closed as the issue is fixed
