### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ipiiia** [xCollateral/VulkanMod#379]
[18:36:33] [Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.class_148: mouseClicked event handler
	at net.minecraft.class_437.method_25412(class_437.java:419) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:180) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:102) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:180) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.2.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.2.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) ~[lwjgl-glfw-3.3.2.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:1616) ~[client-intermediary.jar:?]
	at net.minecraft.class_1041.method_15998(class_1041.java:615) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1349) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[1.20.4-0.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 2, length 0
	at java.lang.String.checkBoundsBeginEnd(String.java:4604) ~[?:?]
	at java.lang.String.substring(String.java:2707) ~[?:?]
	at net.minecraft.class_4717.method_23934(class_4717.java:222) ~[client-intermediary.jar:?]
	at net.minecraft.class_408.method_23945(class_408.java:80) ~[client-intermediary.jar:?]
	at net.minecraft.class_342.method_1874(class_342.java:154) ~[client-intermediary.jar:?]
	at net.minecraft.class_342.method_1883(class_342.java:262) ~[client-intermediary.jar:?]
	at net.minecraft.class_342.method_25348(class_342.java:373) ~[client-intermediary.jar:?]
	at net.minecraft.class_339.method_25402(class_339.java:145) ~[client-intermediary.jar:?]
	at net.minecraft.class_408.method_25402(class_408.java:150) ~[client-intermediary.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:414) ~[client-intermediary.jar:?]
	... 15 more

**Comment by NXTler** [comment]
Provide a full mod list please and a log
