### ISSUE TITLE
crash 2

### ISSUE THREAD

**Issue by ipiiia** [xCollateral/VulkanMod#380]
[21:32:37] [Render thread/ERROR]:
 Reported exception thrown!
net.minecraft.class_148: Rendering Block Entity
	at net.minecraft.class_824.method_3554(class_824.java:111) ~[client-intermediary.jar:?]
	at net.minecraft.class_824.method_3555(class_824.java:79) ~[client-intermediary.jar:?]
	at net.vulkanmod.render.chunk.WorldRenderer.renderBlockEntities(WorldRenderer.java:694) ~[VulkanMod_1.20.4-0.3.9.jar:?]
	at net.minecraft.class_761.handler$cni000$vulkanmod$renderBlockEntities(class_761.java:4725) ~[client-intermediary.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1156) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1098) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:866) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1327) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[1.20.4-0.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
Caused by: java.lang.OutOfMemoryError: Out of stack space.
	at org.lwjgl.system.MemoryStack.nmalloc(MemoryStack.java:322) ~[lwjgl-3.3.2.jar:?]
	at org.lwjgl.system.MemoryStack.mallocLong(MemoryStack.java:474) ~[lwjgl-3.3.2.jar:?]
	at net.vulkanmod.vulkan.shader.Pipeline$DescriptorSets.createDescriptorSets(Pipeline.java:374) ~[VulkanMod_1.20.4-0.3.9.jar:?]
	at net.vulkanmod.vulkan.shader.Pipeline$DescriptorSets.updateDescriptorSet(Pipeline.java:303) ~[VulkanMod_1.20.4-0.3.9.jar:?]
	at net.vulkanmod.vulkan.shader.Pipeline$DescriptorSets.bindSets(Pipeline.java:243) ~[VulkanMod_1.20.4-0.3.9.jar:?]
	at net.vulkanmod.vulkan.shader.Pipeline.bindDescriptorSets(Pipeline.java:190) ~[VulkanMod_1.20.4-0.3.9.jar:?]
	at net.vulkanmod.vulkan.Renderer.uploadAndBindUBOs(Renderer.java:479) ~[VulkanMod_1.20.4-0.3.9.jar:?]
	at net.minecraft.class_286.method_43433(class_286.java:545) ~[client-intermediary.jar:?]
	at net.minecraft.class_1921.method_23012(class_1921.java:881) ~[client-intermediary.jar:?]
	at net.minecraft.class_4597$class_4598.method_22994(class_4597.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_4597$class_4598.getBuffer(class_4597.java:46) ~[client-intermediary.jar:?]
	at net.minecraft.class_327$class_5232.accept(class_327.java:231) ~[client-intermediary.jar:?]
	at net.minecraft.class_5223.method_27477(class_5223.java:17) ~[client-intermediary.jar:?]
	at net.minecraft.class_5223.method_27474(class_5223.java:43) ~[client-intermediary.jar:?]
	at net.minecraft.class_5481.method_30753(class_5481.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_327.method_27530(class_327.java:298) ~[client-intermediary.jar:?]
	at net.minecraft.class_327.method_1723(class_327.java:151) ~[client-intermediary.jar:?]
	at net.minecraft.class_327.method_22942(class_327.java:84) ~[client-intermediary.jar:?]
	at net.minecraft.class_837.method_45798(class_837.java:146) ~[client-intermediary.jar:?]
	at net.minecraft.class_837.method_49920(class_837.java:82) ~[client-intermediary.jar:?]
	at net.minecraft.class_837.method_23083(class_837.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_837.method_3569(class_837.java:41) ~[client-intermediary.jar:?]
	at net.minecraft.class_824.method_23079(class_824.java:90) ~[client-intermediary.jar:?]
	at net.minecraft.class_824.method_23081(class_824.java:79) ~[client-intermediary.jar:?]
	at net.minecraft.class_824.method_3554(class_824.java:104) ~[client-intermediary.jar:?]
	... 12 more

**Comment by NXTler** [comment]
Provide a full mod list please and a log
