### ISSUE TITLE
Minecraft with VulkanMod doesn't start up on Windows 11 ARM64

### ISSUE THREAD

**Issue by h3nda** [xCollateral/VulkanMod#435]
CPU: Snapdragon 860
GPU: Mi Pad 5 Adreno 640

Hello, VulkanMod doesn't work on my Xiaomi Pad 5 with Windows 11 for ARM64 installed. I'm getting error related to DeviceManager. Same happens even if I install official [Microsoft Vulkan compatibility pack from MS Store](https://apps.microsoft.com/detail/9nqpsl29bfff). This device supports Vulkan and [passes this Vulkan test](https://github.com/skeeto/vulkan-test)

```
[11:00:05] [Render thread/INFO]: [STDERR]: java.lang.RuntimeException: Failed to find queue family with transfer support
[11:00:05] [Render thread/INFO]: [STDERR]: 	at net.vulkanmod.vulkan.queue.Queue.findQueueFamilies(Queue.java:153)
[11:00:05] [Render thread/INFO]: [STDERR]: 	at net.vulkanmod.vulkan.device.DeviceManager.isDeviceSuitable(DeviceManager.java:256)
[11:00:05] [Render thread/INFO]: [STDERR]: 	at net.vulkanmod.vulkan.device.DeviceManager.getSuitableDevices(DeviceManager.java:91)
[11:00:05] [Render thread/INFO]: [STDERR]: 	at net.vulkanmod.vulkan.device.DeviceManager.pickPhysicalDevice(DeviceManager.java:100)
[11:00:05] [Render thread/INFO]: [STDERR]: 	at net.vulkanmod.vulkan.device.DeviceManager.init(DeviceManager.java:48)
[11:00:05] [Render thread/INFO]: [STDERR]: 	at net.vulkanmod.vulkan.Vulkan.initVulkan(Vulkan.java:146)
[11:00:05] [Render thread/INFO]: [STDERR]: 	at net.vulkanmod.vulkan.VRenderSystem.initRenderer(VRenderSystem.java:64)
[11:00:05] [Render thread/INFO]: [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:1537)
[11:00:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.class_310.<init>(class_310.java:534)
[11:00:05] [Render thread/INFO]: [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:223)
[11:00:05] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
[11:00:05] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[11:00:05] [Render thread/INFO]: [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[11:00:05] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
[11:00:05] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
[11:00:05] [Render thread/INFO]: [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
---- Minecraft Crash Report ----
// You're mean.

Time: 2024-06-20 11:00:07
Description: Initializing game

java.lang.RuntimeException
	at net.vulkanmod.vulkan.device.DeviceManager.init(DeviceManager.java:54)
	at net.vulkanmod.vulkan.Vulkan.initVulkan(Vulkan.java:146)
	at net.vulkanmod.vulkan.VRenderSystem.initRenderer(VRenderSystem.java:64)
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:1537)
	at net.minecraft.class_310.<init>(class_310.java:534)
	at net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

Full log: https://mclo.gs/V7r2KqP

**Comment by NXTler** [comment]
We don't support arm devices.

**Comment by bagong** [comment]
Really tragic! Think of all the SBCs that can really do with a boost...

**Comment by NXTler** [comment]
We had Android support in one test build for a short time and quickly deleted it again. The reasoning is complex, but to keep it simple - we were getting attention from the android community, which mostly consists of children (you can figure out the rest of the story yourself). It's also extremely hard to maintain arm, because many vendors have broken/outdated drivers.

**Comment by h3nda** [comment]
> We had Android support in one test build for a short time and quickly deleted it again. The reasoning is complex, but to keep it simple - we were getting attention from the android community, which mostly consists of children (you can figure out the rest of the story yourself with this). It's also extremely hard to maintain arm, because many vendors have broken/outdated drivers.

I agree with it. I tested Vulkan 1.2 in Godot-based game and it didn't start at all so probably problem is my Vulkan Hardware Driver. But I can't still understand how to launch Minecraft with VulkanMod and Microsoft Compatibility Pack. As I see, DirectX 12 is much more stable on my device and Microsoft Compatibility Pack can just translate D3D12 to Vulkan 1.2.. So, is there any chance that it will be realized and fixed in future or can I just select render device somehow? Thanks for your answer <3

**Comment by NXTler** [comment]
We have a device selector in the settings, try changing the device in the configuration files.

**Comment by h3nda** [comment]
So, I tried the latest beta GPU drivers and I think I got some progress in it

I got VK_ERROR_OUT_OF_HOST_MEMORY. Seems that a driver problem again because even in Task Manager there's a 1MB of dedicated GPU memory
![image](https://github.com/xCollateral/VulkanMod/assets/90521024/ac41c545-6764-404b-a9fd-9ff4b3ab2565)

Log: https://mclo.gs/wptWByb

**Comment by NXTler** [comment]
I think this can be closed, there is not much we can do for you if that is the case.

**Comment by h3nda** [comment]
Yep, so, closed until driver will be fixed

**Comment by Felix14-v2** [comment]
> Yep, so, closed until driver will be fixed

Actually there's an experimental fork with Adreno support, you can find it if you are not afraid to use test unstable builds.
