### ISSUE TITLE
joining world, resetting icon and pressing cancel crashes

### ISSUE THREAD

**Issue by linux-leo** [xCollateral/VulkanMod#48]
See title.

**Comment by linux-leo** [comment]
I couldn't get a crash report with fabric, but with quilt:

`---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 30/06/2022, 20:22
Description: mouseClicked event handler

java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.system.Library
	at org.lwjgl.opengl.GL.<clinit>(GL.java:80)
	at org.lwjgl.opengl.GL11.<clinit>(GL11.java:38)
	at com.mojang.blaze3d.platform.GlStateManager._deleteTexture(GlStateManager.java:590)
	at com.mojang.blaze3d.platform.TextureUtil.releaseTextureId(TextureUtil.java:49)
	at net.minecraft.class_1060.method_4615(class_1060.java:167)
	at net.minecraft.class_528$class_4272.method_20175(class_528.java:554)
	at net.minecraft.class_528$class_4272.<init>(class_528.java:275)
	at net.minecraft.class_528.method_43454(class_528.java:163)
	at net.minecraft.class_528.method_2750(class_528.java:120)
	at net.minecraft.class_528.<init>(class_528.java:94)
	at net.minecraft.class_526.method_25426(class_526.java:66)
	at net.minecraft.class_437.method_41843(class_437.java:391)
	at net.minecraft.class_437.method_25423(class_437.java:382)
	at net.minecraft.class_310.method_1507(class_310.java:1001)
	at net.minecraft.class_528$class_4272.method_27032(class_528.java:483)
	at net.minecraft.class_524.method_19930(class_524.java:126)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Native Library C:\Users\Claudia\AppData\Local\Temp\lwjglClaudia\3.3.1-SNAPSHOT\lwjgl.dll already loaded in another classloader [in thread "Render thread"]
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:167)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2404)
	at java.base/java.lang.Runtime.load0(Runtime.java:785)
	at java.base/java.lang.System.load(System.java:2009)
	at org.lwjgl.system.Library.loadSystem(Library.java:179)
	at org.lwjgl.system.Library.loadSystemFromLibraryPath(Library.java:169)
	at org.lwjgl.system.Library.loadSystem(Library.java:104)
	at org.lwjgl.system.Library.loadSystem(Library.java:63)
	at org.lwjgl.system.Library.<clinit>(Library.java:51)
	at org.lwjgl.system.jemalloc.JEmalloc.<clinit>(JEmalloc.java:34)
	at org.lwjgl.system.jemalloc.JEmallocAllocator.<clinit>(JEmallocAllocator.java:17)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:383)
	at java.base/java.lang.Class.forName(Class.java:376)
	at org.lwjgl.system.MemoryManage.getInstance(MemoryManage.java:44)
	at org.lwjgl.system.MemoryUtil$LazyInit.<clinit>(MemoryUtil.java:146)
	at org.lwjgl.system.MemoryUtil.getAllocator(MemoryUtil.java:221)
	at net.minecraft.class_311.<clinit>(class_311.java:8)
	at net.minecraft.class_287.<init>(class_287.java:51)
	at net.minecraft.class_289.<init>(class_289.java:19)
	at net.minecraft.class_289.<init>(class_289.java:23)
	at net.minecraft.class_289.<clinit>(class_289.java:11)
	at com.mojang.blaze3d.systems.RenderSystem.<clinit>(RenderSystem.java:46)
	at net.minecraft.client.main.Main.main(Main.java:195)
	... 12 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.lwjgl.opengl.GL.<clinit>(GL.java:80)
	at org.lwjgl.opengl.GL11.<clinit>(GL11.java:38)
	at com.mojang.blaze3d.platform.GlStateManager._deleteTexture(GlStateManager.java:590)
	at com.mojang.blaze3d.platform.TextureUtil.releaseTextureId(TextureUtil.java:49)
	at net.minecraft.class_1060.method_4615(class_1060.java:167)
	at net.minecraft.class_528$class_4272.method_20175(class_528.java:554)
	at net.minecraft.class_528$class_4272.<init>(class_528.java:275)
	at net.minecraft.class_528.method_43454(class_528.java:163)
	at net.minecraft.class_528.method_2750(class_528.java:120)
	at net.minecraft.class_528.<init>(class_528.java:94)
	at net.minecraft.class_526.method_25426(class_526.java:66)
	at net.minecraft.class_437.method_41843(class_437.java:391)
	at net.minecraft.class_437.method_25423(class_437.java:382)
	at net.minecraft.class_310.method_1507(class_310.java:1001)
	at net.minecraft.class_528$class_4272.method_27032(class_528.java:483)
	at net.minecraft.class_524.method_19930(class_524.java:126)
	at net.minecraft.class_4185.method_25306(class_4185.java:40)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_524
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:491)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2295)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 19-ea, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1160015008 bytes (1106 MiB) / 2720006144 bytes (2594 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 6
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2,81
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: NVIDIA GeForce GTX 1050
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048,00
	Graphics card #0 deviceId: 0x1c81
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1165
	Memory slot #0 capacity (MB): 8192,00
	Memory slot #0 clockSpeed (GHz): 2,67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 14623,94
	Virtual memory used (MB): 11229,42
	Swap memory total (MB): 6532,77
	Swap memory used (MB): 784,15
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx4096m
	Quilted Fabric API: !! WARNING !! This instance is using Fabric API modules re-implemented by QSL. If the issue comes from Quilted Fabric API, DO NOT report to Fabric; report them to Quilt instead!
	Quilt Mods: 
		java: OpenJDK 64-Bit Server VM 19
		minecraft: Minecraft 1.19
		org_joml_joml: joml 1.10.4
		org_lwjgl_lwjgl: lwjgl 3.3.1
		org_lwjgl_lwjgl-glfw: lwjgl-glfw 3.3.1
		org_lwjgl_lwjgl-glfw_natives-linux: lwjgl-glfw 3.3.1
		org_lwjgl_lwjgl-glfw_natives-windows: lwjgl-glfw 3.3.1
		org_lwjgl_lwjgl-openal: lwjgl-openal 3.3.1
		org_lwjgl_lwjgl-openal_natives-linux: lwjgl-openal 3.3.1
		org_lwjgl_lwjgl-openal_natives-windows: lwjgl-openal 3.3.1
		org_lwjgl_lwjgl-shaderc: lwjgl-shaderc 3.3.1
		org_lwjgl_lwjgl-shaderc_natives-linux: lwjgl-shaderc 3.3.1
		org_lwjgl_lwjgl-shaderc_natives-windows: lwjgl-shaderc 3.3.1
		org_lwjgl_lwjgl-stb: lwjgl-stb 3.3.1
		org_lwjgl_lwjgl-stb_natives-linux: lwjgl-stb 3.3.1
		org_lwjgl_lwjgl-stb_natives-windows: lwjgl-stb 3.3.1
		org_lwjgl_lwjgl-vma: lwjgl-vma 3.3.1
		org_lwjgl_lwjgl-vma_natives-linux: lwjgl-vma 3.3.1
		org_lwjgl_lwjgl-vma_natives-windows: lwjgl-vma 3.3.1
		org_lwjgl_lwjgl-vulkan: lwjgl-vulkan 3.3.1
		org_lwjgl_lwjgl_natives-linux: lwjgl 3.3.1
		org_lwjgl_lwjgl_natives-windows: lwjgl 3.3.1
		quilt_base: Quilt Base API 2.0.0-beta.9+1.19
		quilt_biome: Quilt Biome API 2.0.0-beta.9+1.19
		quilt_block_entity: Quilt Block Entity API 2.0.0-beta.9+1.19
		quilt_block_extensions: Quilt Block Extensions API 2.0.0-beta.9+1.19
		quilt_client_command: Quilt Client Command API 2.0.0-beta.9+1.19
		quilt_command: Quilt Command API 2.0.0-beta.9+1.19
		quilt_crash_info: Quilt Crash Info 2.0.0-beta.9+1.19
		quilt_dimension: Quilt Dimension API 2.0.0-beta.9+1.19
		quilt_item_group: Quilt Item Group API 2.0.0-beta.9+1.19
		quilt_item_setting: Quilt Item Setting API 2.0.0-beta.9+1.19
		quilt_lifecycle_events: Quilt Lifecycle Events 2.0.0-beta.9+1.19
		quilt_loader: Quilt Loader 0.17.0
		quilt_networking: Quilt Networking 2.0.0-beta.9+1.19
		quilt_recipe: Quilt Recipe API 2.0.0-beta.9+1.19
		quilt_registry: Quilt Registry API 2.0.0-beta.9+1.19
		quilt_registry_entry_attachments: Quilt Registry Entry Attachments 2.0.0-beta.9+1.19
		quilt_resource_loader: Quilt Resource Loader 2.0.0-beta.9+1.19
		quilt_screen: Quilt Screen API 2.0.0-beta.9+1.19
		quilt_tags: Quilt Tags API 2.0.0-beta.9+1.19
		quilt_tooltip: Quilt Tooltip API 2.0.0-beta.9+1.19
		quilted_fabric_api: Quilted Fabric API 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_api_base: Quilted Fabric API Base 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_api_lookup_api_v1: Quilted Fabric API Lookup API (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_biome_api_v1: Quilted Fabric Biome API (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_blockrenderlayer_v1: Quilted Fabric BlockRenderLayer Registration (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_command_api_v1: Quilted Fabric Command API (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_command_api_v2: Quilted Fabric Command API (v2) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_commands_v0: Quilted Fabric Commands (v0) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_containers_v0: Quilted Fabric Containers (v0) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_content_registries_v0: Quilted Fabric Content Registries (v0) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_convention_tags_api_v1: Quilted Fabric Convention Tags API (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_crash_report_info_v1: Quilted Fabric Crash Report Info (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_dimensions_v1: Quilted Fabric Dimensions API (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_entity_events_v1: Quilted Fabric Entity Events (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_events_interaction_v0: Quilted Fabric Events Interaction (v0) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_events_lifecycle_v0: Quilted Fabric Events Lifecycle (v0) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_game_rule_api_v1: Quilted Fabric Game Rule API (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_item_api_v1: Quilted Fabric Item API (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_item_groups_v0: Quilted Fabric Item Groups (v0) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_key_binding_api_v1: Quilted Fabric Key Binding API (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_keybindings_v0: Quilted Fabric Key Bindings (v0) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_lifecycle_events_v1: Quilted Fabric Lifecycle Events (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_loot_api_v2: Quilted Fabric Loot API (v2) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_loot_tables_v1: Quilted Fabric Loot Tables (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_message_api_v1: Quilted Fabric Message API (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_mining_level_api_v1: Quilted Fabric Mining Level API (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_models_v0: Quilted Fabric Models (v0) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_networking_api_v1: Quilted Fabric Networking API (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_networking_v0: Quilted Fabric Networking (v0) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_object_builder_api_v1: Quilted Fabric Object Builder API (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_particles_v1: Quilted Fabric Particles (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_registry_sync_v0: Quilted Fabric Registry Sync (v0) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_renderer_api_v1: Quilted Fabric Renderer API (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_renderer_indigo: Quilted Fabric Renderer - Indigo 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_renderer_registries_v1: Quilted Fabric Renderer Registries (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_rendering_data_attachment_v1: Quilted Fabric Rendering Data Attachment (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_rendering_fluids_v1: Quilted Fabric Rendering Fluids (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_rendering_v0: Quilted Fabric Rendering (v0) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_rendering_v1: Quilted Fabric Rendering (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_resource_conditions_api_v1: Quilted Fabric Resource Conditions API (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_resource_loader_v0: Quilted Fabric Resource Loader (v0) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_screen_api_v1: Quilted Fabric Screen API (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_screen_handler_api_v1: Quilted Fabric Screen Handler API (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_textures_v0: Quilted Fabric Textures (v0) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_transfer_api_v1: Quilted Fabric Transfer API (v1) 2.0.0-beta.3+0.57.0-1.19
		quilted_fabric_transitive_access_wideners_v1: Quilted Fabric Transitive Access Wideners (v1) 2.0.0-beta.3+0.57.0-1.19
		vulkanmod: VulkanMod 0.1.5+2
	Launched Version: 1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'quilt'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz`
