### ISSUE TITLE
VulkanMod crashes minecraft on Prism launcher Flatpak version

### ISSUE THREAD

**Issue by wKaelzx** [xCollateral/VulkanMod#505]
### Describe the bug

I have no idea why it doesnt work with flatpak, maybe it requires some external lib or something that it cant acess from the locked nature of flatpak apps, it doesnt seems to be a problem with my system or the app itself beacuse the app image version works flawless.
I've tested modpacks with vulkanmod, plain vulkanmod and with aditional mods and nothing changes, minecraft only starts when i remove the mod.
Also it seems that its exclusive to 1.21 since the 1.20 version worked.
Vulkanmod installed from Curseforge
Minecraft 1.21.1
Fabric loader 0.16.5
Also this is my first time reporting a bug in GitHub i didnt submited something or did something wrong in general please warn me

### Steps to reproduce

1- Create new minecraft instances 1.21.1 with fabric or quilt
2- Install lasted VulkanMod from curseforge or modrith
3- Starts game 
4- It crashes with error 255

### Log files

---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2024-09-08 09:35:59
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'vulkanmod' at 'net.vulkanmod.Initializer'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NullPointerException
	at org.lwjgl.system.Checks.check(Checks.java:188)
	at org.lwjgl.glfw.GLFW.nglfwGetVideoMode(GLFW.java:1738)
	at org.lwjgl.glfw.GLFW.glfwGetVideoMode(GLFW.java:1761)
	at net.vulkanmod.config.video.VideoModeManager.getCurrentVideoMode(VideoModeManager.java:44)
	at net.vulkanmod.config.video.VideoModeManager.init(VideoModeManager.java:20)
	at net.vulkanmod.Initializer.onInitializeClient(Initializer.java:31)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 9 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:477)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Linux (amd64) version 6.10.7-200.fc40.x86_64
	Java Version: 21.0.4, Flathub
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Flathub
	Memory: 720045024 bytes (686 MiB) / 1073741824 bytes (1024 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 24
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz
	Identifier: Intel64 Family 6 Model 63 Stepping 2
	Microarchitecture: Haswell (Server)
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: Navi 23 [Radeon RX 6600/6600 XT/6600M]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MiB): 258.00
	Graphics card #0 deviceId: 0x73ff
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MiB): 16101.57
	Virtual memory used (MiB): 6823.30
	Swap memory total (MiB): 8192.00
	Swap memory used (MiB): 1.25
	Space in storage for jna.tmpdir (MiB): <path not set>
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set>
	Space in storage for io.netty.native.workdir (MiB): <path not set>
	Space in storage for java.io.tmpdir (MiB): available: 1567.20, total: 1581.91
	Space in storage for workdir (MiB): available: 65098.99, total: 112848.00
	JVM Flags: 2 total; -Xms1024m -Xmx8192m
	Launched Version: 1.21.1
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GFLW Platform: <error>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_BR
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz

**Comment by lv37** [comment]
Make sure you have the `GPU acceleration` option enabled for Prism launcher through Flatseal
![image](https://github.com/user-attachments/assets/85e07d57-f4d4-4408-ab6b-823c4f341e74)
This fixed a similar issue for me.

**Comment by wKaelzx** [comment]
> Make sure you have the `GPU acceleration` option enabled for Prism launcher through Flatseal ![image](https://private-user-images.githubusercontent.com/132778382/365440603-85e07d57-f4d4-4408-ab6b-823c4f341e74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MDE4NDEsIm5iZiI6MTcyNTgwMTU0MSwicGF0aCI6Ii8xMzI3NzgzODIvMzY1NDQwNjAzLTg1ZTA3ZDU3LWY0ZDQtNDQwOC1hYjZiLTgyM2M0ZjM0MWU3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxMzE5MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04M2Q3NmVjZjZhMzk3YmVmYTIzNjQ0MzE3YjBiYmQyYTJmYjZjOTk3MjY1ZjAwOGE5ZDQyMjQ4NTNkZjdlMzgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.11hsrlphQ-vwc-xiQlnWvF39D0H2pF3cXrPHKHi59Nk) This fixed a similar issue for me.

Thanks for the suggestion but it didnt worked

**Comment by lv37** [comment]
try adding `DRI_PRIME=1` to the environment variables for Prism in flatseal (and have the gpu option from before still enabled)
![image](https://github.com/user-attachments/assets/471d56a7-19b8-4310-9286-1a8d7ffd814f)

**Comment by wKaelzx** [comment]
> try adding `DRI_PRIME=1` to the environment variables for Prism in flatseal (and have the gpu option from before still enabled) ![image](https://private-user-images.githubusercontent.com/132778382/365441462-471d56a7-19b8-4310-9286-1a8d7ffd814f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4MDYxMTksIm5iZiI6MTcyNTgwNTgxOSwicGF0aCI6Ii8xMzI3NzgzODIvMzY1NDQxNDYyLTQ3MWQ1NmE3LTE5YjgtNDMxMC05Mjg2LTFhOGQ3ZmZkODE0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQxNDMwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjkzNzE1NTUxZDg1ZTczNDY3ZDQ5ZTEzNDY0OGEzYjU3MTFkZDEzNThmODBiNjY4NjAzYjg3NDc3ODk1ZDJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.u_wnrbNcdYkmrpCEnG9DBtSzCDxh26udqAKBuk-UvHo)

Didnt worked either

**Comment by TacoCake** [comment]
I'm also having this issue, this is the full crash log
[crash_log.txt](https://github.com/user-attachments/files/17175842/crash_log.txt)

I've also tried the Flatseal `GPU Accelration` toggle, no change.

I've been able to **successfully** run `vkcube` in the flatpak sandbox. So I don't think it's a flatpak **dependency** issue. However, installing prismlauncher outside flatpak makes the mod work correctly.

**Comment by NXTler** [comment]
Not a VulkanMod bug, this can be closed.
