### ISSUE TITLE
Lambdynamics Mod Settings Menu crashes Game

### ISSUE THREAD

**Issue by PassiHD2004** [xCollateral/VulkanMod#80]
With VulkanMod loaded, the settings Menu of Lambdynamics crashes the game.

Hardware:
CPU: Intel Xeon X5690
GPU: Nvidia GTX 1060 6GB
RAM: 24GB DDR3
Software Environment: Arch Linux 64bit

`[15:20:28] [Thread-18/ERROR]: Uncaught exception in thread "Thread-18"
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1630) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1628) ~[?:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.core.utils.TransformingIterator.next(TransformingIterator.java:34) ~[lambdynamiclights-2.1.2+1.19.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:57) ~[lambdynamiclights-2.1.2+1.19.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:47) ~[lambdynamiclights-2.1.2+1.19.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:92) ~[lambdynamiclights-2.1.2+1.19.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:47) ~[lambdynamiclights-2.1.2+1.19.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:92) ~[lambdynamiclights-2.1.2+1.19.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:47) ~[lambdynamiclights-2.1.2+1.19.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:92) ~[lambdynamiclights-2.1.2+1.19.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:47) ~[lambdynamiclights-2.1.2+1.19.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:92) ~[lambdynamiclights-2.1.2+1.19.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TableWriter.writeNormal(TableWriter.java:47) ~[lambdynamiclights-2.1.2+1.19.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.toml.TomlWriter.write(TomlWriter.java:30) ~[lambdynamiclights-2.1.2+1.19.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.core.file.WriteAsyncFileConfig.save(WriteAsyncFileConfig.java:114) ~[lambdynamiclights-2.1.2+1.19.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.core.file.WriteAsyncFileConfig.access$300(WriteAsyncFileConfig.java:23) ~[lambdynamiclights-2.1.2+1.19.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.core.file.WriteAsyncFileConfig$WriteCompletedHandler.completed(WriteAsyncFileConfig.java:147) ~[lambdynamiclights-2.1.2+1.19.jar:?]
	at dev.lambdaurora.lambdynlights.shadow.nightconfig.core.file.WriteAsyncFileConfig$WriteCompletedHandler.completed(WriteAsyncFileConfig.java:142) ~[lambdynamiclights-2.1.2+1.19.jar:?]
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129) ~[?:?]
	at sun.nio.ch.SimpleAsynchronousFileChannelImpl$3.run(SimpleAsynchronousFileChannelImpl.java:389) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
FATAL ERROR in native method: Thread[Render thread,10,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL11C.glEnable(Native Method)
	at org.lwjgl.opengl.GL11.glEnable(GL11.java:724)
	at com.mojang.blaze3d.platform.GlStateManager$class_1018.method_4470(GlStateManager.java:883)
	at com.mojang.blaze3d.platform.GlStateManager$class_1018.method_4471(GlStateManager.java:875)
	at com.mojang.blaze3d.platform.GlStateManager._enableScissorTest(GlStateManager.java:56)
	at com.mojang.blaze3d.systems.RenderSystem.enableScissor(RenderSystem.java:255)
	at dev.lambdaurora.spruceui.util.ScissorManager$ScissorHandle.apply(ScissorManager.java:97)
	at dev.lambdaurora.spruceui.util.ScissorManager.push(ScissorManager.java:72)
	at dev.lambdaurora.spruceui.widget.container.SpruceEntryListWidget.renderWidget(SpruceEntryListWidget.java:339)
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25394(AbstractSpruceWidget.java:271)
	at dev.lambdaurora.spruceui.widget.container.tabbed.SpruceTabbedWidget.renderWidget(SpruceTabbedWidget.java:159)
	at dev.lambdaurora.spruceui.widget.AbstractSpruceWidget.method_25394(AbstractSpruceWidget.java:271)
	at dev.lambdaurora.spruceui.screen.SpruceScreen.renderWidgets(SpruceScreen.java:126)
	at dev.lambdaurora.spruceui.screen.SpruceScreen.method_25394(SpruceScreen.java:114)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at java.lang.invoke.LambdaForm$DMH/0x00000008002e8000.invokeStaticInit(java.base@18.0.2/LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/0x00000008002e8400.invokeExact_MT(java.base@18.0.2/LambdaForm$MH)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.lang.invoke.LambdaForm$DMH/0x00000008000c3400.invokeStatic(java.base@18.0.2/LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/0x00000008000c4400.invoke(java.base@18.0.2/LambdaForm$MH)
	at java.lang.invoke.Invokers$Holder.invokeExact_MT(java.base@18.0.2/Invokers$Holder)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(java.base@18.0.2/DirectMethodHandleAccessor.java:155)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(java.base@18.0.2/DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(java.base@18.0.2/Method.java:577)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)
Process crashed with exitcode 6.
`

**Comment by PassiHD2004** [comment]
Other than that it works perfectly fine.

**Comment by Etaash-mathamsetty** [comment]
` No context is current or a function that is not available in the current context was called. The JVM will abort execution. at org.lwjgl.opengl.GL11C.glEnable`
this is due to that mod calling opengl functions, unfortunately this is unfixable

**Comment by PassiHD2004** [comment]
ok, thx for the info
