### ISSUE TITLE
Failed to find GPUs with Vulkan support (Radeon HD 7970)

### ISSUE THREAD

**Issue by Phizilion** [xCollateral/VulkanMod#86]
Radeon HD 7970 support Vulkan 1.1

crush report:

```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 8/13/22, 12:07 PM
Description: Initializing game

java.lang.RuntimeException: Failed to find GPUs with Vulkan support
	at net.vulkanmod.vulkan.Vulkan.pickPhysicalDevice(Vulkan.java:349)
	at net.vulkanmod.vulkan.Vulkan.initVulkan(Vulkan.java:183)
	at net.vulkanmod.vulkan.VRenderSystem.initRenderer(VRenderSystem.java:59)
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:1516)
	at net.minecraft.class_310.<init>(class_310.java:498)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.vulkanmod.vulkan.Vulkan.pickPhysicalDevice(Vulkan.java:349)
	at net.vulkanmod.vulkan.Vulkan.initVulkan(Vulkan.java:183)
	at net.vulkanmod.vulkan.VRenderSystem.initRenderer(VRenderSystem.java:59)
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:1516)
	at net.minecraft.class_310.<init>(class_310.java:498)

-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 5.15.59-1-MANJARO
	Java Version: 17.0.4, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1711900688 bytes (1632 MiB) / 2025848832 bytes (1932 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
	Identifier: Intel64 Family 6 Model 42 Stepping 7
	Microarchitecture: unknown
	Frequency (GHz): 3.40
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Tahiti XT [Radeon HD 7970/8970 OEM / R9 280X]
	Graphics card #0 vendor: Advanced Micro Devices, Inc. [AMD/ATI] (0x1002)
	Graphics card #0 VRAM (MB): 256.00
	Graphics card #0 deviceId: 0x6798
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 10049.18
	Virtual memory used (MB): 5344.97
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms409m -Xmx4096m
	Launched Version: 1.18.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
```

**Comment by Phizilion** [comment]
try last build (https://github.com/xCollateral/VulkanMod/actions/runs/2823812879), same error

**Comment by xCollateral** [comment]
Maybe you need to update mesa drivers or maybe mesa doesn't support vulkan on your gpu.
However mesa drivers have got issues getting the correct swapchain image index, this makes VulkanMod perform really bad, always if it works and doesn't crash.

**Comment by Phizilion** [comment]
> Maybe you need to update mesa drivers or maybe mesa doesn't support vulkan on your gpu. However mesa drivers have got issues getting the correct swapchain image index, this makes VulkanMod perform really bad, always if it works and doesn't crash.

I fixed the problem by installing a Vulkan compatible driver for my gpu, specifically `amdgpu-experemental`
https://forum.manjaro.org/t/dx11-issues-starting-proton-games/110971
