### ISSUE TITLE
Just crash on 1.17.1

### ISSUE THREAD

**Issue by kirieshka1725** [xCollateral/VulkanMod#88]
Game launched and immediately crushing 

Win - 10, Java - 17.0.4, Vulkan - 1.17-0.1.4+3, tried it first on Quilt loader 0.17.3, then on Fabric loader 0.14.9(similar crah)

`[13:50:15] [Render thread/ERROR]: Minecraft has crashed!
org.quiltmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:425) ~[quilt-loader-0.17.3.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76) [quilt-loader-0.17.3.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) [quilt-loader-0.17.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_4494.method_22089(class_4494.java:541) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37123(class_6396.java:65) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_37274(class_310.java:2462) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_22681(class_310.java:2412) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:187) ~[minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) ~[quilt-loader-0.17.3.jar:?]
	... 11 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.lwjgl.vulkan.VkPhysicalDeviceProperties.vendorID()" because "net.vulkanmod.vulkan.Vulkan.deviceProperties" is null
	at net.vulkanmod.vulkan.DeviceInfo.<clinit>(DeviceInfo.java:20) ~[VulkanMod_1.17-0.1.4+3.jar:?]
	at net.minecraft.class_4494.method_22089(class_4494.java:541) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37123(class_6396.java:65) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_37274(class_310.java:2462) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_22681(class_310.java:2412) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:187) ~[minecraft-1.17.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423) ~[quilt-loader-0.17.3.jar:?]
	... 11 more`

**Comment by xCollateral** [comment]
Is it happening on new version?
